Run it Twice: src/EquityCalculator.cpp File Reference
EquityCalculator.cpp File Reference
#include "EquityCalculator.hpp"
Functions
string getFileStartPath ()
bool fileExists (const std::string &filename)
vector< float > findEquity (const std::string &filename, const std::vector< std::string > &searchValues)
Function Documentation
fileExists()
bool fileExists (const std::string & filename)
Definition at line 43 of file EquityCalculator.cpp.
{
     struct stat buffer;
     return (stat(filename.c_str(), &buffer) == 0);
 }
Referenced by EquityCalculator::calculateHandEquity(), and TEST_F().
findEquity()
vector<float> findEquity (const std::string & filename, const std::vector< std::string > & searchValues)
Definition at line 48 of file EquityCalculator.cpp.
{
     vector<float> equity;
     std::ifstream file(filename);
     if (!file.is_open()) {
         std::cerr << "Error opening file: " << filename << std::endl;
         return equity;
     }
     std::string line;
     while (std::getline(file, line)) {
         std::stringstream ss(line);
         std::string field;
         std::vector<std::string> row;
         while (std::getline(ss, field, ',')) {
             row.push_back(field);
         }
         if (row.size() >= 6) {
             bool match = true;
             for (size_t i = 0; i < 4; ++i) {
                 if (i >= searchValues.size() || row[i] != searchValues[i]) {
                     match = false;
                     break;
                 }
             }
             if (match) {
                 file.close();
                 equity.push_back(stof(row[4]));
                 equity.push_back(stof(row[5]));
                 return equity;
             }
         }
     }
     file.close();
     return equity;
 }
Referenced by EquityCalculator::calculateHandEquity().
getFileStartPath()
string getFileStartPath ()
Definition at line 9 of file EquityCalculator.cpp.
{
     // Get os type
 #ifdef _WIN32
     std::string os = "Windows";
 #elif __APPLE__
     std::string os = "MacOS";
 #elif __linux__
     std::string os = "Linux";
 #else
     std::string os = "Unknown";
 #endif
     string startPath;
     if (os == "Windows")
     {
         startPath = "../../..";
     }
     else if (os == "MacOS")
     {
         startPath = "..";
     }
     else if (os == "Linux")
     {
         startPath = "..";
     }
     else
     {
         std::cerr << "Unsupported OS" << std::endl;
         return "";
     }
     return startPath;
 }
Referenced by EquityCalculator::buildPreflopEquityCSV(), EquityCalculator::calculateHandEquity(), and TEST_F().