Run it Twice: src/GUI.cpp File Reference
GUI.cpp File Reference
#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <sstream>
#include "Card.hpp"
#include "Player.hpp"
#include "GUI.hpp"
#include "Game.hpp"
#include "CSVWorker.hpp"
Functions
void moveTo (int x, int y)
string getFilePathStart ()
string addString (string baseString, string newString, int x1, int y1)
string getFileContents (string filePath)
string getCardString (Card &card)
Function Documentation
addString()
string addString (string baseString, string newString, int x1, int y1)
Definition at line 379 of file GUI.cpp.
{
    // Split the base string and new string into lines
    vector<string> baseLines;
    vector<string> newLines;
    stringstream ssBase(baseString), ssNew(newString);
    string line;
    while (getline(ssBase, line))
    {
        baseLines.push_back(line);
    }
    while (getline(ssNew, line))
    {
        newLines.push_back(line);
    }
    // Ensure the replacement does not go out of bounds
    for (int i = 0; i < newLines.size(); i++)
    {
        int targetLine = y1 + i;
        if (targetLine < baseLines.size())
        {
            string &baseLine = baseLines[targetLine];
            string &newLine = newLines[i];
            if (x1 < baseLine.size())
            {
                // Replace the part of the line starting from x1 with the new string
                baseLine.replace(x1, newLine.size(), newLine);
            }
            else
            {
                // If x1 is outside the base line, just append the new string
                baseLine.append(string(x1 - baseLine.size(), ' ') + newLine);
            }
        }
    }
    // Recombine the base lines into a single string
    string result;
    for (const string &baseLine : baseLines)
    {
        result += baseLine + "\n";
    }
    return result;
}
Referenced by GUI::displayGameState().
getCardString()
string getCardString (Card & card)
Definition at line 445 of file GUI.cpp.
{
    string suit = card.get_suit();
    string rank = card.get_rank();
    string startPath = getFilePathStart();
    string cardPath = startPath + "/images/" + suit + "Card.txt";
    string cardContent = getFileContents(cardPath);
    // Replace a ? with the rank of the card
    int start = 0;
    for(int i = 0; i < 2; i++){
        size_t pos = cardContent.find("?", start);
        if(rank != "10"){
            cardContent.replace(pos, 1, rank);
        } else if(i == 0){
            cardContent.replace(pos, 2, rank);
        }else{
            cardContent.replace(pos-1, 2, rank);
        }
        start = pos + 1;
    }
    return cardContent;
}
References Card::get_rank(), Card::get_suit(), getFileContents(), and getFilePathStart().
Referenced by GUI::displayGameState().
getFileContents()
string getFileContents (string filePath)
Definition at line 428 of file GUI.cpp.
{
    // Get the contents of the file at the file path
    std::ifstream file(filePath);
    if (!file) {
        std::cerr << "Error opening file!" << std::endl;
        return "";
    }
    // Read the file into a string
    std::ostringstream oss;
    oss << file.rdbuf();
    std::string content = oss.str();
    file.close();
    return content;
}
Referenced by GUI::displayGameState(), getCardString(), and GUI::getRandomPlayerName().
getFilePathStart()
string getFilePathStart ()
Definition at line 185 of file GUI.cpp.
{
    // Get os type
    #ifdef _WIN32
        std::string os = "Windows";
    #elif __APPLE__
        std::string os = "MacOS";
    #elif __linux__
        std::string os = "Linux";
    #else
        std::string os = "Unknown";
    #endif
    string startPath;
    if (os == "Windows")
    {
        startPath = "../../..";
    }
    else if (os == "MacOS")
    {
        startPath = "..";
    }
    else if (os == "Linux")
    {
        startPath = "..";
    }
    else
    {
        std::cerr << "Unsupported OS" << std::endl;
        return "";
    }
    return startPath;
}
Referenced by GUI::displayEndMessage(), GUI::displayGameState(), getCardString(), and GUI::getRandomPlayerName().
moveTo()
void moveTo (int x, int y)
Definition at line 52 of file GUI.cpp.
{
    std::cout << "\033[" << y << ";" << x << "H";
}
Referenced by GUI::displayEndMessage(), and GUI::displayGameState().