Bluron: TestGame Class Reference
TestGame Class Reference
Public Member Functions
void setUp ()
void tareDown ()
void test_add_player ()
void test_deal_hands ()
void test ()
Private Attributes
Game * game
vector< Player * > players
Detailed Description
Definition at line 7 of file test_Game.cpp.
Member Function Documentation
setUp()
void TestGame::setUp () inline
Definition at line 13 of file test_Game.cpp.
                      {
             Player *player1 = new Player("Jess", 1000);
             Player *player2 = new Player("John", 1000);
             players.push_back(player1);
             players.push_back(player2);
             game = new Game(players);
         }
References game, and players.
Referenced by test_add_player(), and test_deal_hands().
tareDown()
void TestGame::tareDown () inline
Definition at line 22 of file test_Game.cpp.
{
             delete game;
             for (Player *player : players) {
                 delete player;
             }
         }
References game, and players.
Referenced by test_add_player(), and test_deal_hands().
test()
void TestGame::test () inline
Definition at line 191 of file test_Game.cpp.
                     {
             test_add_player();
             test_deal_hands();
             // test_deal_flop();
             // test_deal_turn();
             // test_deal_river();
             // test_getPlayers();
             // test_get_community_cards();
             // test_get_deck();
             // test_playHand();
             // test_makeMoveForUser();
             // test_getCurrentMove();
             // test_addBlindsToPot();
         }
References test_add_player(), and test_deal_hands().
Referenced by main().
test_add_player()
void TestGame::test_add_player () inline
Definition at line 29 of file test_Game.cpp.
{
             setUp();
             Player *player3 = new Player("James", 1000);
             game->add_player(player3);
             assert(game->getPlayers().size() == 3 && "Player was not added");
             tareDown();
         }
References Game::add_player(), game, Game::getPlayers(), setUp(), and tareDown().
Referenced by test().
test_deal_hands()
void TestGame::test_deal_hands () inline
Definition at line 38 of file test_Game.cpp.
{
             setUp();
             game->deal_hands();
             // Asserting each player has 2 cards in hand
             for (Player *player : game->getPlayers()) {
                 assert(player->get_hand().size() == 2 && "Player does not have 2 cards in hand");
             }
             // Asserting deck has 48 cards
             Deck deck = game->get_deck();
             assert(deck.get_cards().size() == 48 && "Deck does not have 48 cards");
             tareDown();
         }
References Game::deal_hands(), game, Deck::get_cards(), Game::getPlayers(), setUp(), and tareDown().
Referenced by test().
Field Documentation
game
Game* TestGame::game private
Definition at line 9 of file test_Game.cpp.
Referenced by setUp(), tareDown(), test_add_player(), and test_deal_hands().
players
vector<Player*> TestGame::players private
Definition at line 10 of file test_Game.cpp.
Referenced by setUp(), and tareDown().
The documentation for this class was generated from the following file:
tests/test_Game.cpp