Run it Twice: BetterPlayer Class Reference
BetterPlayer Class Reference
Public Member Functions
BetterPlayer (const std::string &name, int stack)
std::string getMove (bool canCheck, bool canRaise, bool canFold, bool canCall, vector< Card > community_cards, int largestBet, int numPlayersInHand, int pot) override
Gets the player's move during their turn.
int getBetSizing (int minBet, int maxBet) override
Gets the player's bet sizing during their turn.
int endOfHand ()
Handles actions at the end of a hand.
BetterPlayer (const std::string &name, int stack)
std::string getMove (bool canCheck, bool canRaise, bool canFold, bool canCall, vector< Card > community_cards, int largestBet, int numPlayersInHand, int pot) override
Gets the player's move during their turn.
int getBetSizing (int minBet, int maxBet) override
Gets the player's bet sizing during their turn.
int endOfHand ()
Handles actions at the end of a hand.
Public Member Functions inherited from Player
Player (const std::string &name, int stack)
Constructs a Player object with a given name and stack.
void bet (int amount)
Places a bet by the player.
int deduct_blind (int amount)
Deducts a blind amount from the player's stack.
void win (int amount)
Adds a winning amount to the player's stack.
int get_stack ()
Gets the current stack of the player.
string get_name ()
Gets the name of the player.
vector< Card > get_hand ()
Gets the player's current hand of cards.
void add_card_to_hand (Card card)
Adds a card to the player's hand.
void clear_hand ()
Clears the player's hand of all cards.
void show_hand ()
Displays the player's current hand.
int get_current_bet ()
Gets the player's current bet in the ongoing hand.
int get_total_bet ()
Gets the total amount the player has bet this hand.
void setTotalBet (int amount)
Sets the total amount the player has bet this hand.
void reset_current_bet ()
Resets the player's current bet to zero.
void reset_total_bet ()
Resets the total amount the player has bet this hand to zero. This is used at the end of a hand to reset the player's total bet.
vector< float > get_equity (vector< Card > communityCards, int numPlayers)
Returns the equity of the players hand for the current stage of the game.
Private Attributes
std::default_random_engine rng
int pot
Additional Inherited Members
Static Public Member Functions inherited from Player
static bool test_player ()
Tests the Player class functionality.
static string generate_random_name ()
Generates a random name for the player.
Detailed Description
Definition at line 9 of file BetterPlayer 2.cpp.
Constructor & Destructor Documentation
BetterPlayer() [1/2]
BetterPlayer::BetterPlayer (const std::string & name, int stack) inline
Definition at line 14 of file BetterPlayer 2.cpp.
                                                    : Player(name, stack) {
         unsigned seed = std::chrono::system_clock::now().time_since_epoch().count();
         rng.seed(seed);
     }
References rng.
BetterPlayer() [2/2]
BetterPlayer::BetterPlayer (const std::string & name, int stack) inline
Definition at line 16 of file BetterPlayer.cpp.
                                                    : Player(name, stack)
     {
         unsigned seed = std::chrono::system_clock::now().time_since_epoch().count();
         rng.seed(seed);
     }
References rng.
Member Function Documentation
endOfHand() [1/2]
int BetterPlayer::endOfHand () inline virtual
Handles actions at the end of a hand.
Returns
The outcome of the end-of-hand process.
Implements Player.
Definition at line 68 of file BetterPlayer 2.cpp.
                     {
         return 1;
     }
endOfHand() [2/2]
int BetterPlayer::endOfHand () inline virtual
Handles actions at the end of a hand.
Returns
The outcome of the end-of-hand process.
Implements Player.
Definition at line 80 of file BetterPlayer.cpp.
     {
         return 1;
     }
getBetSizing() [1/2]
int BetterPlayer::getBetSizing (int minBet, int maxBet) inline override virtual
Gets the player's bet sizing during their turn.
Parameters
minBet The minimum bet allowed.
maxBet The maximum bet allowed.
Returns
The player's chosen bet size.
Implements Player.
Definition at line 52 of file BetterPlayer 2.cpp.
{
         // randomly flip a coin until it is false and count the number of flips
         int count = 0;
         while(true){
             int flip = (rand()%5)+ 1 ;
             if (flip == 1){
                break;
             }
             count++;
         }
         // TESTING: print the bet sizing
         // std::cout << min(minBet*(count+1), maxBet) << std::endl;
         return min(minBet*(count+1), 10000);
     }
getBetSizing() [2/2]
int BetterPlayer::getBetSizing (int minBet, int maxBet) inline override virtual
Gets the player's bet sizing during their turn.
Parameters
minBet The minimum bet allowed.
maxBet The maximum bet allowed.
Returns
The player's chosen bet size.
Implements Player.
Definition at line 57 of file BetterPlayer.cpp.
{
         // Randomly choose a bet size that is either 1/4, 1/3, 1/2 or full pot
         std::uniform_int_distribution<int> betSize(1, 4);
         int bet = 0;
         switch(betSize(rng)){
             case 1:
                 bet = pot/4;
                 break;
             case 2:
                 bet = pot/3;
                 break;
             case 3:
                 bet = pot/2;
                 break;
             case 4:
                 bet = pot;
                 break;
         }
         return max(minBet, min(maxBet, bet));
     }
References Player::bet(), pot, and rng.
getMove() [1/2]
std::string BetterPlayer::getMove (bool canCheck, bool canRaise, bool canFold, bool canCall, vector< Card > community_cards, int largestBet, int numPlayersInHand, int pot) inline override virtual
Gets the player's move during their turn.
Parameters
canCheck Whether the player can check.
canRaise Whether the player can raise.
canFold Whether the player can fold.
canCall Whether the player can call.
Returns
The player's chosen move as a string.
Implements Player.
Definition at line 19 of file BetterPlayer 2.cpp.
{
         // Get the bros equity from the equity calculator
         vector<float> equity = get_equity(community_cards, numPlayersInHand);
         double equityThreshold = 1.0/numPlayersInHand;
         equityThreshold *= 1.1;
         // If the equity is below the threshold, fold
         if (equity[0] < equityThreshold) {
             if(canFold){
                 return "f";
             } else {
                 return "a";
             }
         }
         if(canCall){
             // Radomly generate a double to decide whether to raise or call
             std::uniform_real_distribution<double> dist(0.0, 1.0);
             double randNum = dist(rng);
             if(equity[0] >= equityThreshold*1.5 && randNum > 0.4 && largestBet < 10000){
                 return "r";
             } else {
                 return "c";
             }
         }
         if(largestBet < 10000){
             return "r";
         }
         return "a";
     }
References Player::get_equity(), and rng.
getMove() [2/2]
std::string BetterPlayer::getMove (bool canCheck, bool canRaise, bool canFold, bool canCall, vector< Card > community_cards, int largestBet, int numPlayersInHand, int pot) inline override virtual
Gets the player's move during their turn.
Parameters
canCheck Whether the player can check.
canRaise Whether the player can raise.
canFold Whether the player can fold.
canCall Whether the player can call.
Returns
The player's chosen move as a string.
Implements Player.
Definition at line 22 of file BetterPlayer.cpp.
     {
         this->pot = pot;
         // Get the bros equity from the equity calculator
         vector<float> equity = get_equity(community_cards, numPlayersInHand);
         double equityThreshold = 1.0 / numPlayersInHand * 1.15;
         // If the equity is below the threshold, fold
         if (equity[0] < equityThreshold)
         {
             if (canFold)
             {
                 return "f";
             }
             else
             {
                 return "a";
             }
         }
         if (canCall)
         {
             if (equity[0] >= equityThreshold * 1.25)
             {
                 return "r";
             }
             else
             {
                 return "c";
             }
         }
         return "r";
     }
References Player::get_equity(), and pot.
Field Documentation
pot
int BetterPlayer::pot private
Definition at line 13 of file BetterPlayer.cpp.
Referenced by getBetSizing(), and getMove().
rng
std::default_random_engine BetterPlayer::rng private
Definition at line 11 of file BetterPlayer 2.cpp.
Referenced by BetterPlayer(), getBetSizing(), and getMove().
The documentation for this class was generated from the following files:
src/BetterPlayer 2.cpp
src/BetterPlayer.cpp