Run it Twice: HumanPlayerTest Class Reference
HumanPlayerTest Class Reference
Protected Member Functions
void SetUp () override
void TearDown () override
Detailed Description
Definition at line 9 of file test_HumanPlayer.cc.
Member Function Documentation
SetUp()
void HumanPlayerTest::SetUp () inline override protected
Definition at line 11 of file test_HumanPlayer.cc.
{
        // Replace the real GUI with our mock
        GUI::getUserMove = MockGUI::getUserMove;
        GUI::getBetSizing = MockGUI::getBetSizing;
        GUI::endOfRoundMenu = MockGUI::endOfRoundMenu;
    }
References GUI::endOfRoundMenu(), GUI::getBetSizing(), and GUI::getUserMove().
TearDown()
void HumanPlayerTest::TearDown () inline override protected
Definition at line 18 of file test_HumanPlayer.cc.
{
        // Reset the GUI functions to their original implementations if needed
    }
The documentation for this class was generated from the following file:
tests/test_HumanPlayer.cc