Run it Twice: GUIWrapper Class Reference
GUIWrapper Class Reference
Public Member Functions
virtual ~GUIWrapper ()=default
virtual std::string getUserMove (bool canCheck, bool canRaise, bool canFold, bool canCall)
virtual int getBetSizing (int minBet, int maxBet)
virtual int endOfRoundMenu ()
Detailed Description
Definition at line 6 of file test_HumanPlayer.cc.
Constructor & Destructor Documentation
~GUIWrapper()
virtual GUIWrapper::~GUIWrapper () virtual default
Member Function Documentation
endOfRoundMenu()
virtual int GUIWrapper::endOfRoundMenu () inline virtual
Definition at line 18 of file test_HumanPlayer.cc.
     {
         return GUI::endOfRoundMenu();
     }
References GUI::endOfRoundMenu().
Referenced by HumanPlayer::endOfHand().
getBetSizing()
virtual int GUIWrapper::getBetSizing (int minBet, int maxBet) inline virtual
Definition at line 14 of file test_HumanPlayer.cc.
     {
         return GUI::getBetSizing(minBet, maxBet);
     }
References GUI::getBetSizing().
Referenced by HumanPlayer::getBetSizing().
getUserMove()
virtual std::string GUIWrapper::getUserMove (bool canCheck, bool canRaise, bool canFold, bool canCall) inline virtual
Definition at line 10 of file test_HumanPlayer.cc.
     {
         return GUI::getUserMove(canCheck, canRaise, canFold, canCall);
     }
References GUI::getUserMove().
Referenced by HumanPlayer::getMove().
The documentation for this class was generated from the following file:
tests/test_HumanPlayer.cc