Run it Twice: CSVWorker Class Reference
CSVWorker Class Reference
#include <CSVWorker.hpp>
Public Member Functions
CSVWorker (const std::string &fname)
bool writeProfiles ()
std::vector< PlayerProfile > readProfiles ()
void addProfile (const PlayerProfile &profile)
const std::vector< PlayerProfile > & getProfiles () const
void printProfiles () const
void updateProfile (const PlayerProfile &profile)
Private Attributes
std::string filename
std::vector< PlayerProfile > profiles
Detailed Description
Definition at line 9 of file CSVWorker.hpp.
Constructor & Destructor Documentation
CSVWorker()
CSVWorker::CSVWorker (const std::string & fname)
Definition at line 8 of file CSVWorker.cpp.
 : filename(fname) {}
Member Function Documentation
addProfile()
void CSVWorker::addProfile (const PlayerProfile & profile)
Definition at line 77 of file CSVWorker.cpp.
{
     profiles.push_back(profile);
 }
References profiles.
Referenced by GUI::createProfile().
getProfiles()
const std::vector< PlayerProfile > & CSVWorker::getProfiles () const
Definition at line 81 of file CSVWorker.cpp.
{
     return profiles;
 }
References profiles.
printProfiles()
void CSVWorker::printProfiles () const
Definition at line 96 of file CSVWorker.cpp.
{
     for (const auto& profile : profiles) {
         std::cout << "Name: " << profile.name
                     << ", Total Hands Played: " << profile.totalHandsPlayed
                     << ", Easy Hands: " << profile.numHandsEasy
                     << ", Medium Hands: " << profile.numHandsMedium
                     << ", Hard Hands: " << profile.numHandsHard
                     << ", Easy Pnl: " << profile.easyPnl
                     << ", Medium Pnl: " << profile.mediumPnl
                     << ", Hard Pnl: " << profile.hardPnl
                     << ", VPIP Hands: " << profile.numHandsVpip << std::endl;
     }
 }
References profiles.
readProfiles()
std::vector< PlayerProfile > CSVWorker::readProfiles ()
Definition at line 33 of file CSVWorker.cpp.
{
     // Opening the file in read mode
     std::ifstream file(filename);
     if (!file.is_open()) {
         return std::vector<PlayerProfile>();
     }
     profiles.clear();
     std::string line;
     getline(file, line); // Skip header
     // Populating the profiles vector with the profiles in the file
     while (getline(file, line)) {
         std::istringstream ss(line);
         std::string field;
         PlayerProfile profile;
         getline(ss, profile.name, ',');
         getline(ss, field, ',');
         profile.totalHandsPlayed = std::stoi(field);
         getline(ss, field, ',');
         profile.numHandsEasy = std::stoi(field);
         getline(ss, field, ',');
         profile.numHandsMedium = std::stoi(field);
         getline(ss, field, ',');
         profile.numHandsHard = std::stoi(field);
         getline(ss, field, ',');
         profile.easyPnl = std::stoi(field);
         getline(ss, field, ',');
         profile.mediumPnl = std::stoi(field);
         getline(ss, field, ',');
         profile.hardPnl = std::stoi(field);
         getline(ss, field, ',');
         profile.numHandsVpip = std::stoi(field);
         profiles.push_back(profile);
     }
     // Closing the file and returning the profiles
     file.close();
     return profiles;
 }
References PlayerProfile::easyPnl, filename, PlayerProfile::hardPnl, PlayerProfile::mediumPnl, PlayerProfile::name, PlayerProfile::numHandsEasy, PlayerProfile::numHandsHard, PlayerProfile::numHandsMedium, PlayerProfile::numHandsVpip, profiles, and PlayerProfile::totalHandsPlayed.
Referenced by GUI::createProfile(), GUI::getProfile(), and updateProfile().
updateProfile()
void CSVWorker::updateProfile (const PlayerProfile & profile)
Definition at line 85 of file CSVWorker.cpp.
{
     this->readProfiles();
     for (auto& p : profiles) {
         if (p.name == profile.name) {
             p = profile;
             break;
         }
     }
     this->writeProfiles();
 }
References PlayerProfile::name, profiles, readProfiles(), and writeProfiles().
Referenced by playGame().
writeProfiles()
bool CSVWorker::writeProfiles ()
Definition at line 10 of file CSVWorker.cpp.
{
     std::ofstream file(filename);
     if (!file.is_open()) {
         return false;
     }
     file << "Name,TotalHandsPlayed,NumHandsEasy,NumHandsMedium,NumHandsHard,EasyPnl,MediumPnl,HardPnl,NumHandsVpip\n";
     for (const auto& profile : profiles) {
         file << profile.name << ","
              << profile.totalHandsPlayed << ","
                 << profile.numHandsEasy << ","
                 << profile.numHandsMedium << ","
                 << profile.numHandsHard << ","
                 << profile.easyPnl << ","
                 << profile.mediumPnl << ","
                 << profile.hardPnl << ","
                 << profile.numHandsVpip << "\n";
     }
     file.close();
     return true;
 }
References filename, and profiles.
Referenced by GUI::createProfile(), and updateProfile().
Field Documentation
filename
std::string CSVWorker::filename private
Definition at line 12 of file CSVWorker.hpp.
Referenced by readProfiles(), and writeProfiles().
profiles
std::vector<PlayerProfile> CSVWorker::profiles private
Definition at line 13 of file CSVWorker.hpp.
Referenced by addProfile(), getProfiles(), printProfiles(), readProfiles(), updateProfile(), and writeProfiles().
The documentation for this class was generated from the following files:
src/CSVWorker.hpp
src/CSVWorker.cpp