Run it Twice: TestPlayer Class Reference
TestPlayer Class Reference
Public Member Functions
void setUp ()
void tareDown ()
void test_add_card_to_hand ()
void test_clear_hand ()
void test_get_stack ()
void test_get_hand ()
void test_get_name ()
void test_show_hand ()
void test_player ()
Private Attributes
Player * player
Card * AceOfHearts
Card * AceOfSpades
Detailed Description
Definition at line 5 of file test_Player.cpp.
Member Function Documentation
setUp()
void TestPlayer::setUp () inline
Definition at line 12 of file test_Player.cpp.
                      {
             player = new Player("Jess", 1000);
             AceOfHearts = new Card("Hearts", "Ace");
             AceOfSpades = new Card("Spades", "Ace");
         }
References AceOfHearts, AceOfSpades, and player.
Referenced by test_add_card_to_hand(), test_clear_hand(), test_get_hand(), test_get_name(), test_get_stack(), and test_show_hand().
tareDown()
void TestPlayer::tareDown () inline
Definition at line 19 of file test_Player.cpp.
{
             delete player;
             delete AceOfHearts;
             delete AceOfSpades;
         }
References AceOfHearts, AceOfSpades, and player.
Referenced by test_add_card_to_hand(), test_clear_hand(), test_get_hand(), test_get_name(), test_get_stack(), and test_show_hand().
test_add_card_to_hand()
void TestPlayer::test_add_card_to_hand () inline
Definition at line 25 of file test_Player.cpp.
{
             setUp();
             player->add_card_to_hand(*AceOfHearts);
             player->add_card_to_hand(*AceOfSpades);
             assert(player->get_hand().size() == 2 && "Hand size is not 2");
             tareDown();
         }
References AceOfHearts, AceOfSpades, Player::add_card_to_hand(), Player::get_hand(), player, setUp(), and tareDown().
Referenced by test_player().
test_clear_hand()
void TestPlayer::test_clear_hand () inline
Definition at line 34 of file test_Player.cpp.
{
             setUp();
             player->clear_hand();
             assert(player->get_hand().size() == 0 && "Hand size is not 0");
             tareDown();
         }
References Player::clear_hand(), Player::get_hand(), player, setUp(), and tareDown().
Referenced by test_player().
test_get_hand()
void TestPlayer::test_get_hand () inline
Definition at line 48 of file test_Player.cpp.
{
             setUp();
             player->add_card_to_hand(*AceOfHearts);
             player->add_card_to_hand(*AceOfSpades);
             assert(player->get_hand()[0].get_suit() == "Hearts" && player->get_hand()[0].get_rank() == "Ace" && "Card is not correct");
             assert(player->get_hand()[1].get_suit() == "Spades" && player->get_hand()[1].get_rank() == "Ace" && "Card is not correct");
             tareDown();
         }
References AceOfHearts, AceOfSpades, Player::add_card_to_hand(), Player::get_hand(), player, setUp(), and tareDown().
Referenced by test_player().
test_get_name()
void TestPlayer::test_get_name () inline
Definition at line 58 of file test_Player.cpp.
{
             setUp();
             assert(player->get_name() == "Jess" && "Name is not Jess");
             tareDown();
         }
References Player::get_name(), player, setUp(), and tareDown().
Referenced by test_player().
test_get_stack()
void TestPlayer::test_get_stack () inline
Definition at line 42 of file test_Player.cpp.
{
             setUp();
             assert(player->get_stack() == 1000 && "Stack is not 1000");
             tareDown();
         }
References Player::get_stack(), player, setUp(), and tareDown().
Referenced by test_player().
test_player()
void TestPlayer::test_player () inline
Definition at line 73 of file test_Player.cpp.
{
             test_add_card_to_hand();
             test_clear_hand();
             test_get_stack();
             test_get_hand();
             test_get_name();
             test_show_hand();
         }
References test_add_card_to_hand(), test_clear_hand(), test_get_hand(), test_get_name(), test_get_stack(), and test_show_hand().
Referenced by main().
test_show_hand()
void TestPlayer::test_show_hand () inline
Definition at line 64 of file test_Player.cpp.
{
             setUp();
             player->add_card_to_hand(*AceOfHearts);
             player->add_card_to_hand(*AceOfSpades);
             player->show_hand();
             tareDown();
         }
References AceOfHearts, AceOfSpades, Player::add_card_to_hand(), player, setUp(), Player::show_hand(), and tareDown().
Referenced by test_player().
Field Documentation
AceOfHearts
Card* TestPlayer::AceOfHearts private
Definition at line 8 of file test_Player.cpp.
Referenced by setUp(), tareDown(), test_add_card_to_hand(), test_get_hand(), and test_show_hand().
AceOfSpades
Card* TestPlayer::AceOfSpades private
Definition at line 9 of file test_Player.cpp.
Referenced by setUp(), tareDown(), test_add_card_to_hand(), test_get_hand(), and test_show_hand().
player
Player* TestPlayer::player private
Definition at line 7 of file test_Player.cpp.
Referenced by setUp(), tareDown(), test_add_card_to_hand(), test_clear_hand(), test_get_hand(), test_get_name(), test_get_stack(), and test_show_hand().
The documentation for this class was generated from the following file:
tests/test_Player.cpp