Bluron: Card Class Reference
Card Class Reference
Represents a single card in a deck of cards. Each card has a suit and a rank.
#include <Card.hpp>
Public Member Functions
Card (const std::string &suit, const std::string &rank)
Constructs a Card object with the given suit and rank.
const std::string get_suit ()
Gets the suit of the card.
const std::string get_rank ()
Gets the rank of the card.
const std::string get_card ()
Gets the card's representation as a string.
Static Public Member Functions
static bool test_card ()
Tests the Card class functionality.
Data Fields
std::string suit
The suit of the card (e.g., Hearts, Diamonds).
std::string rank
The rank of the card (e.g., Ace, King, 7).
Detailed Description
Represents a single card in a deck of cards. Each card has a suit and a rank.
Example usage:
Card card = Card("Hearts", "Ace");
Definition at line 14 of file Card.hpp.
Constructor & Destructor Documentation
Card()
Card::Card (const std::string & suit, const std::string & rank)
Constructs a Card object with the given suit and rank.
Parameters
suit The suit of the card.
rank The rank of the card.
Constructor for the Card class. Initializes a card with a given suit and rank.
Parameters
suit The suit of the card (e.g., "Hearts").
rank The rank of the card (e.g., "Ace").
Definition at line 18 of file Card.cpp.
 : suit(suit), rank(rank) {}
Referenced by test_card().
Member Function Documentation
get_card()
const string Card::get_card ()
Gets the card's representation as a string.
Returns
A string representing the card (e.g., "Ace of Hearts").
Definition at line 38 of file Card.cpp.
{
     return rank + " of " + suit;
 }
References rank, and suit.
get_rank()
const string Card::get_rank ()
Gets the rank of the card.
Returns
The rank of the card as a string.
Getter for the rank of the card.
Returns
The rank of the card.
Definition at line 34 of file Card.cpp.
{
     return rank;
 }
References rank.
Referenced by getCardString(), Deck::remove_card(), test_card(), and test_card().
get_suit()
const string Card::get_suit ()
Gets the suit of the card.
Returns
The suit of the card as a string.
Getter for the suit of the card.
Returns
The suit of the card.
Definition at line 25 of file Card.cpp.
{
     return suit;
 }
References suit.
Referenced by getCardString(), Deck::remove_card(), test_card(), and test_card().
test_card()
bool Card::test_card () static
Tests the Card class functionality.
Returns
True if the test passes, otherwise false.
A static method to test the Card class.
Definition at line 45 of file Card.cpp.
                      {
     Card card = Card("Hearts", "Ace");
     if (card.get_suit() != "Hearts") {
         return false;
     }
     if (card.get_rank() != "Ace") {
         return false;
     }
     return true;
 }
References Card(), get_rank(), and get_suit().
Referenced by uniTest().
Field Documentation
rank
std::string Card::rank
The rank of the card (e.g., Ace, King, 7).
Definition at line 17 of file Card.hpp.
Referenced by get_card(), and get_rank().
suit
std::string Card::suit
The suit of the card (e.g., Hearts, Diamonds).
Definition at line 16 of file Card.hpp.
Referenced by get_card(), and get_suit().
The documentation for this class was generated from the following files:
src/Card.hpp
src/Card.cpp