Run it Twice: HumanPlayer Class Reference
HumanPlayer Class Reference
#include <HumanPlayer.hpp>
Public Member Functions
HumanPlayer (const std::string &name, int stack)
std::string getMove (bool canCheck, bool canRaise, bool canFold, bool canCall) override
Gets the player's move during their turn.
int getBetSizing (int minBet, int maxBet) override
Gets the player's bet sizing during their turn.
int endOfHand ()
Handles actions at the end of a hand.
std::string getMove (bool canCheck, bool canRaise, bool canFold, bool canCall)
Gets the human player's move during their turn by calling the getPlayerMove method in GUI class.
int getBetSizing (int minBet, int maxBet)
Gets the human player's bet sizing during their turn.
int endOfHand ()
Handles actions at the end of a hand for a human player.
HumanPlayer (const std::string &name, int stack, GUIWrapper *wrapper)
std::string getMove (bool canCheck, bool canRaise, bool canFold, bool canCall) override
Gets the player's move during their turn.
int getBetSizing (int minBet, int maxBet) override
Gets the player's bet sizing during their turn.
int endOfHand ()
Handles actions at the end of a hand.
Public Member Functions inherited from Player
Player (const std::string &name, int stack)
Constructs a Player object with a given name and stack.
void bet (int amount)
Places a bet by the player.
int deduct_blind (int amount)
Deducts a blind amount from the player's stack.
void win (int amount)
Adds a winning amount to the player's stack.
int get_stack ()
Gets the current stack of the player.
string get_name ()
Gets the name of the player.
vector< Card > get_hand ()
Gets the player's current hand of cards.
void add_card_to_hand (Card card)
Adds a card to the player's hand.
void clear_hand ()
Clears the player's hand of all cards.
void show_hand ()
Displays the player's current hand.
int get_current_bet ()
Gets the player's current bet in the ongoing hand.
void reset_current_bet ()
Resets the player's current bet to zero.
Private Attributes
GUIWrapper * guiWrapper
Additional Inherited Members
Static Public Member Functions inherited from Player
static bool test_player ()
Tests the Player class functionality.
Detailed Description
Definition at line 4 of file HumanPlayer.cpp.
Constructor & Destructor Documentation
HumanPlayer() [1/2]
HumanPlayer::HumanPlayer (const std::string & name, int stack) inline
Definition at line 6 of file HumanPlayer.cpp.
 : Player(name, stack) {}
HumanPlayer() [2/2]
HumanPlayer::HumanPlayer (const std::string & name, int stack, GUIWrapper * wrapper) inline
Definition at line 38 of file test_HumanPlayer.cc.
         : Player(name, stack), guiWrapper(wrapper) {}
Member Function Documentation
endOfHand() [1/3]
int HumanPlayer::endOfHand () inline virtual
Handles actions at the end of a hand.
Returns
The outcome of the end-of-hand process.
Implements Player.
Definition at line 18 of file HumanPlayer.cpp.
                     {
         return GUI::endOfRoundMenu();
     }
References GUI::endOfRoundMenu().
endOfHand() [2/3]
int HumanPlayer::endOfHand () virtual
Handles actions at the end of a hand for a human player.
Returns
The outcome of the end-of-hand process.
Implements Player.
endOfHand() [3/3]
int HumanPlayer::endOfHand () inline virtual
Handles actions at the end of a hand.
Returns
The outcome of the end-of-hand process.
Implements Player.
Definition at line 51 of file test_HumanPlayer.cc.
     {
         return guiWrapper->endOfRoundMenu();
     }
References GUIWrapper::endOfRoundMenu(), and guiWrapper.
getBetSizing() [1/3]
int HumanPlayer::getBetSizing (int minBet, int maxBet) virtual
Gets the human player's bet sizing during their turn.
Parameters
minBet The minimum bet allowed.
maxBet The maximum bet allowed.
Returns
The player's chosen bet size.
Implements Player.
getBetSizing() [2/3]
int HumanPlayer::getBetSizing (int minBet, int maxBet) inline override virtual
Gets the player's bet sizing during their turn.
Parameters
minBet The minimum bet allowed.
maxBet The maximum bet allowed.
Returns
The player's chosen bet size.
Implements Player.
Definition at line 13 of file HumanPlayer.cpp.
{
         // Call GUI to get bet sizing
         return GUI::getBetSizing(minBet, maxBet);
     }
References GUI::getBetSizing().
getBetSizing() [3/3]
int HumanPlayer::getBetSizing (int minBet, int maxBet) inline override virtual
Gets the player's bet sizing during their turn.
Parameters
minBet The minimum bet allowed.
maxBet The maximum bet allowed.
Returns
The player's chosen bet size.
Implements Player.
Definition at line 46 of file test_HumanPlayer.cc.
     {
         return guiWrapper->getBetSizing(minBet, maxBet);
     }
References GUIWrapper::getBetSizing(), and guiWrapper.
getMove() [1/3]
std::string HumanPlayer::getMove (bool canCheck, bool canRaise, bool canFold, bool canCall) virtual
Gets the human player's move during their turn by calling the getPlayerMove method in GUI class.
Parameters
canCheck Whether the player can check.
canRaise Whether the player can raise.
canFold Whether the player can fold.
canCall Whether the player can call.
Returns
The player's chosen move as a string.
Implements Player.
getMove() [2/3]
std::string HumanPlayer::getMove (bool canCheck, bool canRaise, bool canFold, bool canCall) inline override virtual
Gets the player's move during their turn.
Parameters
canCheck Whether the player can check.
canRaise Whether the player can raise.
canFold Whether the player can fold.
canCall Whether the player can call.
Returns
The player's chosen move as a string.
Implements Player.
Definition at line 8 of file HumanPlayer.cpp.
{
         // Call GUI to get user move
         return GUI::getUserMove(canCheck, canRaise, canFold, canCall);
     }
References GUI::getUserMove().
getMove() [3/3]
std::string HumanPlayer::getMove (bool canCheck, bool canRaise, bool canFold, bool canCall) inline override virtual
Gets the player's move during their turn.
Parameters
canCheck Whether the player can check.
canRaise Whether the player can raise.
canFold Whether the player can fold.
canCall Whether the player can call.
Returns
The player's chosen move as a string.
Implements Player.
Definition at line 41 of file test_HumanPlayer.cc.
     {
         return guiWrapper->getUserMove(canCheck, canRaise, canFold, canCall);
     }
References GUIWrapper::getUserMove(), and guiWrapper.
Field Documentation
guiWrapper
GUIWrapper* HumanPlayer::guiWrapper private
Definition at line 35 of file test_HumanPlayer.cc.
Referenced by endOfHand(), getBetSizing(), and getMove().
The documentation for this class was generated from the following files:
src/HumanPlayer.cpp
tests/test_HumanPlayer.cc
src/HumanPlayer.hpp