Run it Twice: GUI Class Reference
GUI Class Reference
Provides a graphical user interface for interacting with the poker game.
#include <GUI.hpp>
Static Public Member Functions
static void setGame (Game *game)
Sets the game object for the GUI.
static Game & getGame ()
Gets the game object for the GUI.
static PlayerProfile signInMenu ()
Prompts the user to sign in.
static int getNumberOfPlayers ()
Gets the number of players from the user.
static int getBotDifficulty ()
static void clearScreen ()
Clears the console screen.
static string getRandomPlayerName ()
Generate a random name for a player.
static string getUserMove (bool canCheck, bool canRaise, bool canFold, bool canCall)
Prompts the user for their move.
static int getBetSizing (int minBet, int maxBet)
Prompts the user for bet sizing.
static void displayAllPlayerHands (const std::vector< Player * > &players)
Displays the hands of all players.
static void displayCommunityCards (const std::vector< Card > &community_cards)
Displays the community cards on the table.
static void displayPlayerStack (Player *player)
Displays the current chip stack of a player.
static void displayPlayerHand (Player *player)
Displays the hand of a player.
static void displayStartScreen ()
Displays the start screen of the game.
static void displayEndMessage ()
Displays the end message when the game is over.
static void displayPlayerStats (PlayerProfile profile)
Displays the winner of the game.
static MenuOption displayMenu ()
Displays the main menu of the game.
static string getFilePathStart ()
static MenuOption displayRules ()
static void optionToViewStats (PlayerProfile profile)
Displays the menu to view player stats.
static int endOfRoundMenu ()
Displays the menu at the end of a round.
static void displayGameState (vector< Player * > winners)
Displays the current state of the game.
static void displayGameState ()
static void displayPlayerMove (Player *player, string move, int size)
Displays a player's move.
static PlayerProfile chooseAccount ()
Displays input to the user to create a profile.
Static Public Attributes
static const Point PLAYER_CARD_POSITIONS [8][2]
Positions for player cards.
static const Point COMMUNITY_CARD_POSITIONS [5] = { {84, 23}, {92, 23}, {100, 23}, {108, 23}, {116, 23} }
Positions for community cards.
static const Point PLAYER_NAME_POSITIONS [8] = { {104, 46}, {54, 39}, {32, 26}, {54, 10}, {104, 9}, {154, 10}, {175, 26}, {154, 39} }
Positions for player names.
static const Point PLAYER_CURRENT_BETS [8] = { {104, 36}, {62, 34}, {50, 26}, {62, 17}, {104, 15}, {146, 17}, {158, 26}, {146, 34} }
Positions for player current bets.
static const Point PLAYER_BUTTON_POSITIONS [8] = { {112, 36}, {68, 36}, {50, 28}, {54, 18}, {94, 15}, {138, 15}, {158, 24}, {152, 32} }
Positions for player buttons.
static const Point PLAYER_EQUITY_POSITION [2] = {{10, 10}, {10, 11}}
Positions for player equity.
Static Private Member Functions
static PlayerProfile createProfile ()
Creates a new player profile.
static PlayerProfile getProfile (const std::string &name)
Gets the profile of a player from the ./data/profiles.csv file.
Static Private Attributes
static Game * game = nullptr
Pointer to the game object used for getting game state information.
Detailed Description
Provides a graphical user interface for interacting with the poker game.
Definition at line 34 of file GUI.hpp.
Member Function Documentation
chooseAccount()
static PlayerProfile GUI::chooseAccount () static
Displays input to the user to create a profile.
clearScreen()
void GUI::clearScreen () static
Clears the console screen.
Clear the terminal screen
Definition at line 61 of file GUI.cpp.
                       {
     // Check the os of the user
     #ifdef _WIN32
         system("cls");
     #else
         system("clear");
     #endif
 }
Referenced by displayEndMessage(), displayRules(), displayStartScreen(), and playGame().
createProfile()
PlayerProfile GUI::createProfile () static private
Creates a new player profile.
Returns
The newly created player profile.
Definition at line 709 of file GUI.cpp.
{
     string startPath = GUI::getFilePathStart();
     CSVWorker csv(startPath + "/data/profiles.csv");
     // Check if a profile exists in the CSV file
     std::string name;
     int age;
     std::cout << "Enter your name: ";
     std::cin >> name;
     PlayerProfile playerProfile = { name };
     csv.readProfiles();
     csv.addProfile(playerProfile);
     csv.writeProfiles();
     return playerProfile;
 }
References CSVWorker::addProfile(), getFilePathStart(), CSVWorker::readProfiles(), and CSVWorker::writeProfiles().
Referenced by signInMenu().
displayAllPlayerHands()
void GUI::displayAllPlayerHands (const std::vector< Player * > & players) static
Displays the hands of all players.
Parameters
players A vector of pointers to the players whose hands will be displayed.
Display all player hands to the terminal
Parameters
players vector<Player*> - Players to display hands for
Definition at line 165 of file GUI.cpp.
{
     for (Player* player : players) {
         std::cout << player->get_name() << "'s hand: " << std::endl;
         for (Card& card : player->get_hand()) {
             std::cout << card.get_rank() << " of " << card.get_suit() << std::endl;
         }
         std::cout << "--------------" << std::endl;
     }
 }
displayCommunityCards()
void GUI::displayCommunityCards (const std::vector< Card > & community_cards) static
Displays the community cards on the table.
Parameters
community_cards A vector of community cards to be displayed.
Display community cards to the terminal
Parameters
community_cards vector<Card> - Community cards to display
Definition at line 153 of file GUI.cpp.
{
     // Display community cards
     for (Card card : community_cards) {
         std::cout << card.get_rank() << " of " << card.get_suit() << std::endl;
     }
 }
displayEndMessage()
void GUI::displayEndMessage () static
Displays the end message when the game is over.
Definition at line 235 of file GUI.cpp.
{
     clearScreen();
     string startPath = GUI::getFilePathStart();
     string imagePath = startPath + "/images/cardAnimation.txt";
     string delimiter = "[END OF FRAME]\n";
     int delay = 25;
     std::ifstream inputFile(imagePath);
     if (!inputFile) {
         std::cerr << "Error opening file!" << std::endl;
         return;
     }
     // Read the file into a string
     std::ostringstream oss;
     oss << inputFile.rdbuf();
     std::string content = oss.str();
     inputFile.close();
     std::vector<std::string> frames;
     size_t start = 0;
     size_t end;
     // Split the frames
     while ((end = content.find(delimiter, start)) != std::string::npos) {
         frames.push_back(content.substr(start, end - start));
         start = end + delimiter.length();
     }
     frames.push_back(content.substr(start)); // Add the last frame
     for (int i = 0; i < 5; i++) {
         // Print each frame with a delay
         for (const std::string& frame : frames) {
             std::cout << frame << std::endl;
             std::this_thread::sleep_for(std::chrono::milliseconds(delay));
             moveTo(0, 0);
         }
     }
     displayStartScreen();
     //std::cout << imageASCII << std::endl;
     std::cout << "--------------------------------" << std::endl;
 }
References clearScreen(), displayStartScreen(), getFilePathStart(), and moveTo().
Referenced by playGame().
displayGameState() [1/2]
void GUI::displayGameState () static
Definition at line 525 of file GUI.cpp.
{
     vector<Player*> winners;
     GUI::displayGameState(winners);
 }
Referenced by Game::bettingRound(), displayPlayerMove(), playGame(), and Game::playHand().
displayGameState() [2/2]
void GUI::displayGameState (vector< Player * > winners) static
Displays the current state of the game.
Definition at line 530 of file GUI.cpp.
{
     Game game = getGame();
     vector<Player*> players = game.getPlayers();
     vector<Card> communityCards = game.getCommunityCards();
     int button = game.getButton();
     moveTo(0, 0);
     // TODO: Implement this method, will be called as each hand progresses and display
     // table, chips, cards, stack sizes, players names, etc.
     // Get the contents of the table.txt file and print it to the terminal
     string startPath = GUI::getFilePathStart();
     string tablePath = startPath + "/images/table.txt";
     string tableContent = getFileContents(tablePath);
     string buttonPath = startPath + "/images/button.txt";
     string buttonString = getFileContents(buttonPath);
     for(int i = 0; i < communityCards.size(); i++){
         string cardContent = getCardString(communityCards[i]);
         tableContent = addString(tableContent, cardContent, COMMUNITY_CARD_POSITIONS[i].x, COMMUNITY_CARD_POSITIONS[i].y);
     }
     tableContent = addString(tableContent, "Pot: " + std::to_string(game.getPot()), 103 - (std::to_string(game.getPot()).length() + 5)/2, 21);
     int numPlayers = players.size();
     int seatStep = 8 / numPlayers;
     for(int i = 0; i < numPlayers; i++){
         tableContent = addString(tableContent, players[i]->get_name(), PLAYER_NAME_POSITIONS[i * seatStep].x - players[i]->get_name().length()/2, PLAYER_NAME_POSITIONS[i * seatStep].y);
         tableContent = addString(tableContent, "Stack: " + std::to_string(players[i]->get_stack()), PLAYER_NAME_POSITIONS[i * seatStep].x -((7 + std::to_string(players[i]->get_stack()).length() )/2), PLAYER_NAME_POSITIONS[i * seatStep].y + 2);
          if(players[i]->get_current_bet() != 0){
             tableContent = addString(tableContent, "Bet: " + std::to_string(players[i]->get_current_bet()), PLAYER_CURRENT_BETS[i * seatStep].x -((5 + std::to_string(players[i]->get_current_bet()).length() )/2), PLAYER_CURRENT_BETS[i * seatStep].y);
          }
          if(i == button){
             tableContent = addString(tableContent, buttonString, PLAYER_BUTTON_POSITIONS[i * seatStep].x, PLAYER_BUTTON_POSITIONS[i * seatStep].y);
          }
          if (players[i]->get_hand().size() != 0) {
              string playerCardContent1;
              string playerCardContent2;
              if (i == 0 || game.getShowdown()) {
                 playerCardContent1 = getCardString(players[i]->get_hand()[0]);
                 playerCardContent2 = getCardString(players[i]->get_hand()[1]);
              }
              else {
                  playerCardContent1 = getFileContents(startPath + "/images/backCard.txt");
                  playerCardContent2 = playerCardContent1;
              }
              // Add the card to the table content
              tableContent = addString(tableContent, playerCardContent1, PLAYER_CARD_POSITIONS[i * seatStep][0].x, PLAYER_CARD_POSITIONS[i* seatStep][0].y);
              tableContent = addString(tableContent, playerCardContent2, PLAYER_CARD_POSITIONS[i * seatStep][1].x, PLAYER_CARD_POSITIONS[i* seatStep][1].y);
          }
          else {
              // Show that they have folded
          }
     }
     if (winners.size() > 0) {
         string winnersString = winners[0]->get_name();
         for (int i = 1; i < winners.size(); i++) {
             winnersString += " and ";
             winnersString += winners[i]->get_name();
         }
         winnersString += " Won the game.";
         tableContent = addString(tableContent, winnersString, 105 - winnersString.size()/2, 0);
     }
     std::cout << tableContent << std::endl;
     moveTo(0, 0);
 }
References addString(), COMMUNITY_CARD_POSITIONS, game, Game::getButton(), getCardString(), Game::getCommunityCards(), getFileContents(), getFilePathStart(), getGame(), Game::getPlayers(), Game::getPot(), Game::getShowdown(), moveTo(), PLAYER_BUTTON_POSITIONS, PLAYER_CARD_POSITIONS, PLAYER_CURRENT_BETS, and PLAYER_NAME_POSITIONS.
displayMenu()
MenuOption GUI::displayMenu () static
Displays the main menu of the game.
Returns
The selected menu option as an integer.
Definition at line 283 of file GUI.cpp.
{
     vector<string> acceptedInputs = {"", "p", "q", "1", "2", "3", "r"};
     std::cout << "1. Start Game (press Enter)" << std::endl;
     std::cout << "2. View rules (r)" << std::endl;
     std::cout << "3. Quit (q)" << std::endl;
     std::string input;
     std::getline(std::cin, input);  // Read the entire line, allowing us to detect Enter
     // While the user input is not in acceptedInputs, prompt the user for a valid input
     while (std::find(acceptedInputs.begin(), acceptedInputs.end(), input) == acceptedInputs.end()) {
         std::cout << "Invalid input. Please enter a valid option: ";
         std::getline(std::cin, input);  // Use getline to capture the next input
     }
     // Handle the user input
     switch (input[0]) {
         case 'q':
             return QUIT;
         case '3':
             return QUIT;
         case 'r':
             return GUI::displayRules();
         case '2':
             return GUI::displayRules();
         default:
             return START_GAME;
     }
 }
References displayRules(), QUIT, and START_GAME.
Referenced by displayRules(), and playGame().
displayPlayerHand()
void GUI::displayPlayerHand (Player * player) static
Displays the hand of a player.
Parameters
player Pointer to the player whose hand will be displayed.
Display a player's hand to the terminal
Parameters
player Player* - Player to display hand for
Definition at line 180 of file GUI.cpp.
{
     std::cout << player->get_name() << "'s hand: " << std::endl;
     for (Card card : player->get_hand()) {
         std::cout << card.get_rank() << " of " << card.get_suit() << std::endl;
     }
     std::cout << "--------------" << std::endl;
 }
References Player::get_hand(), and Player::get_name().
displayPlayerMove()
void GUI::displayPlayerMove (Player * player, string move, int size) static
Displays a player's move.
Parameters
player Pointer to the player making the move.
move The move made by the player as a string.
size The bet size associated with the move.
Definition at line 607 of file GUI.cpp.
{
     displayGameState();
     if (size != -1) { move += " " + to_string(size); }
     cout << player->get_name() << ": " << move << endl;
 }
References displayGameState(), and Player::get_name().
Referenced by Game::makeMoveForUser().
displayPlayerStack()
void GUI::displayPlayerStack (Player * player) static
Displays the current chip stack of a player.
Parameters
player Pointer to the player whose stack will be displayed.
Definition at line 442 of file GUI.cpp.
{
     std::cout << player->get_name() << "'s stack: " << player->get_stack() << std::endl;
     std::cout << "    -----    " << std::endl;
 }
References Player::get_name(), and Player::get_stack().
displayPlayerStats()
void GUI::displayPlayerStats (PlayerProfile profile) static
Displays the winner of the game.
Parameters
player Pointer to the winning player.
Definition at line 673 of file GUI.cpp.
{
     if(player.totalHandsPlayed == 0){
         std::cout << "No hands played yet! Play some hands to view your statistics <3" << std::endl;
         return;
     }
     std::cout << "Name: " << player.name << std::endl;
     std::cout << "Total hands played: " << player.totalHandsPlayed << "\n" << std::endl;
     if(player.numHandsEasy != 0){
         std::cout << "Easy hands played: " << player.numHandsEasy << std::endl;
         std::cout << "Easy PnL per 100 hands: " << (player.easyPnl / player.numHandsEasy)*100.0 << "\n" <<std::endl;
     } else {
         std::cout << "No easy hands played" << "\n" << std::endl;
     }
     if(player.numHandsMedium != 0){
         std::cout << "Medium hands played: " << player.numHandsMedium << std::endl;
         std::cout << "Medium PnL per 100 hands: " << (player.mediumPnl / player.numHandsMedium)*100.0 << "\n" << std::endl;
     } else {
         std::cout << "No medium hands played" << "\n" << std::endl;
     }
     if(player.numHandsHard != 0){
         std::cout << "Hard hands played: " << player.numHandsHard << std::endl;
         std::cout << "Hard PnL per 100 hands: " << (player.hardPnl / player.numHandsHard)*100.0 << "\n" << std::endl;
     } else {
         std::cout << "No hard hands played" << "\n" << std::endl;
     }
     std::cout << "VPIP: " << (player.numHandsVpip/player.totalHandsPlayed)*100 << "%" <<std::endl;
     return;
 }
References PlayerProfile::easyPnl, PlayerProfile::hardPnl, PlayerProfile::mediumPnl, PlayerProfile::name, PlayerProfile::numHandsEasy, PlayerProfile::numHandsHard, PlayerProfile::numHandsMedium, PlayerProfile::numHandsVpip, and PlayerProfile::totalHandsPlayed.
Referenced by optionToViewStats().
displayRules()
MenuOption GUI::displayRules () static
Definition at line 314 of file GUI.cpp.
{
     string startPath = GUI::getFilePathStart();
     string rulesPath = startPath + "/images/pokerTutorial.txt";
    string rules = getFileContents(rulesPath);
    cout << rules + "\n" << endl;
     cout << "Press Enter to return to the main menu" << endl;
     std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
     // clear the screen
     clearScreen();
     // display the start screen
     displayStartScreen();
     MenuOption m = GUI::displayMenu();
     return m;
 }
References clearScreen(), displayMenu(), displayStartScreen(), getFileContents(), and getFilePathStart().
Referenced by displayMenu().
displayStartScreen()
void GUI::displayStartScreen () static
Displays the start screen of the game.
Definition at line 188 of file GUI.cpp.
{
     string title = R"(:::::::::  :::    ::: ::::    :::    ::::::::::: :::::::::::    ::::::::::: :::       ::: :::::::::::  ::::::::  ::::::::::
 :+:    :+: :+:    :+: :+:+:   :+:        :+:         :+:            :+:     :+:       :+:     :+:     :+:    :+: :+:
 +:+    +:+ +:+    +:+ :+:+:+  +:+        +:+         +:+            +:+     +:+       +:+     +:+     +:+        +:+
 +#++:++#:  +#+    +:+ +#+ +:+ +#+        +#+         +#+            +#+     +#+  +:+  +#+     +#+     +#+        +#++:++#
 +#+    +#+ +#+    +#+ +#+  +#+#+#        +#+         +#+            +#+     +#+ +#+#+ +#+     +#+     +#+        +#+
 #+#    #+# #+#    #+# #+#   #+#+#        #+#         #+#            #+#      #+#+# #+#+#      #+#     #+#    #+# #+#
 ###    ###  ########  ###    ####    ###########     ###            ###       ###   ###   ###########  ########  ########## )";
     clearScreen();
     std::cout << title << std::endl;
     std::cout << "--------------------------------" << std::endl;
 }
References clearScreen().
Referenced by displayEndMessage(), displayRules(), and playGame().
endOfRoundMenu()
int GUI::endOfRoundMenu () static
Displays the menu at the end of a round.
Returns
The selected menu option as an integer.
Definition at line 417 of file GUI.cpp.
{
     std::cout << "1. Continue (enter)" << std::endl;
     std::cout << "2. Main menu (m)" << std::endl;
     std::cout << "3. Quit (q)" << std::endl;
     std::string input;
     std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
     std::getline(std::cin, input);  // Read the entire line, allowing us to detect Enter
     while (input != "q" && input != "" && input != "m" && input != "1" && input != "2" && input != "3") {
         std::cout << "Invalid input. Please enter a valid option: ";
         std::getline(std::cin, input);  // Use getline to capture the next input
     }
     if (input == "q" || input == "3") {
         return 0;
     }
     if(input == "m" || input == "2"){
         return 2;
     }
     return 1;
 }
Referenced by HumanPlayer::endOfHand(), and HumanPlayerTest::SetUp().
getBetSizing()
int GUI::getBetSizing (int minBet, int maxBet) static
Prompts the user for bet sizing.
Parameters
minBet The minimum bet allowed.
maxBet The maximum bet allowed.
Returns
The bet size chosen by the user.
Get user bet sizing from the terminal
Parameters
minBet int - Minimum bet size
maxBet int - Maximum bet size
Definition at line 121 of file GUI.cpp.
{
     // Get user bet size
     // TODO: Test bet sizing input validation
     int bet_sizing;
     std::cout << "Enter your bet sizing: ";
     while (true) {
         std::cin >> bet_sizing;
         // Check if the input is valid
         if (std::cin.fail()) {
             std::cin.clear(); // Clear the error state
             std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n'); // Discard invalid input
             std::cout << "Invalid input. Please enter a valid integer bet size: ";
             continue;
         }
         // Check if the bet is within the valid range
         if (bet_sizing >= minBet && bet_sizing <= maxBet) {
             break; // Valid bet size
         }
         std::cout << "Invalid bet size. Please enter a bet size between " << minBet << " and " << maxBet << ": ";
     }
     return bet_sizing;
 }
Referenced by HumanPlayer::getBetSizing(), and HumanPlayerTest::SetUp().
getBotDifficulty()
int GUI::getBotDifficulty () static
Definition at line 353 of file GUI.cpp.
{
     std::cout << "Enter the bot difficulty (Easy (1), Medium (2), Hard (3)): ";
     int difficulty;
     // Asking the user for the number of players - bounded between 2 and 8
     do {
         std::cin >> difficulty;
         // Check if the input is valid
         if (std::cin.fail() || difficulty < 1 || difficulty > 3) {
             std::cin.clear(); // Clear the error state
             std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n'); // Discard invalid input
             std::cout << "Invalid input. Please enter a number between 1 and 3: ";
         }
     } while (difficulty < 1 || difficulty > 3);
     return difficulty;
 }
Referenced by playGame().
getFilePathStart()
string GUI::getFilePathStart () static
Definition at line 201 of file GUI.cpp.
{
     // Get os type
     #ifdef _WIN32
         std::string os = "Windows";
     #elif __APPLE__
         std::string os = "MacOS";
     #elif __linux__
         std::string os = "Linux";
     #else
         std::string os = "Unknown";
     #endif
     string startPath;
     if (os == "Windows")
     {
         startPath = "../../..";
     }
     else if (os == "MacOS")
     {
         startPath = "..";
     }
     else if (os == "Linux")
     {
         startPath = "..";
     }
     else
     {
         std::cerr << "Unsupported OS" << std::endl;
         return "";
     }
     return startPath;
 }
Referenced by createProfile(), displayEndMessage(), displayGameState(), displayRules(), getCardString(), getProfile(), getRandomPlayerName(), and playGame().
getGame()
Game & GUI::getGame () static
Gets the game object for the GUI.
Returns
Reference to the game object.
Definition at line 37 of file GUI.cpp.
                    {
     return *GUI::game;
 }
References game.
Referenced by displayGameState().
getNumberOfPlayers()
int GUI::getNumberOfPlayers () static
Gets the number of players from the user.
Returns
The number of players as an integer.
Definition at line 333 of file GUI.cpp.
{
     std::cout << "Enter the number of players: ";
     int numPlayers;
     // Asking the user for the number of players - bounded between 2 and 8
     do {
         std::cin >> numPlayers;
         // Check if the input is valid
         if (std::cin.fail() || numPlayers < 2 || numPlayers > 8) {
             std::cin.clear(); // Clear the error state
             std::cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n'); // Discard invalid input
             std::cout << "Invalid input. Please enter a number between 2 and 8: ";
         }
     } while (numPlayers < 2 || numPlayers > 8);
     return numPlayers;
 }
Referenced by playGame().
getProfile()
PlayerProfile GUI::getProfile (const std::string & name) static private
Gets the profile of a player from the ./data/profiles.csv file.
Parameters
name The name of the player.
Returns
The profile of the player.
Definition at line 729 of file GUI.cpp.
{
     string startPath = GUI::getFilePathStart();
     CSVWorker csv(startPath + "/data/profiles.csv");
     // Get the user's profile that has the name entered
     for (PlayerProfile profile : csv.readProfiles()) {
         if (profile.name == name) {
             return profile;
         }
     }
     cout << "Profile not found." << endl;
     return signInMenu();
 }
References getFilePathStart(), CSVWorker::readProfiles(), and signInMenu().
Referenced by signInMenu().
getRandomPlayerName()
std::string GUI::getRandomPlayerName () static
Generate a random name for a player.
Returns
The randomly generated name as a string.
Definition at line 613 of file GUI.cpp.
{
     std::string startPath = GUI::getFilePathStart();
     // Get the contents of the adjectives.txt file
     std::string adjectives = getFileContents(startPath + "/images/adjectives.txt");
     // Split the adjective string into lines
     std::vector<std::string> adjectiveList;
     std::stringstream ssAdjectives(adjectives);
     std::string adjective;
     while (std::getline(ssAdjectives, adjective)) {
         adjectiveList.push_back(adjective);
     }
     // Get the contents of the animals.txt file
     std::string animals = getFileContents(startPath + "/images/animals.txt");
     // Split the animals string into lines
     std::vector<std::string> animalList;
     std::stringstream ssAnimals(animals);
     std::string animal;
     while (std::getline(ssAnimals, animal)) {
         animalList.push_back(animal);
     }
     // Initialize random number generator statically so it's only seeded once
     auto seed = std::chrono::system_clock::now().time_since_epoch().count();
     std::mt19937 gen(static_cast<unsigned long>(seed));  // Seeding the generator
     // Randomly pick an adjective and animal from the lists
     std::uniform_int_distribution<> distrAdjective(0, adjectiveList.size() - 1);
     std::string randomAdjective = adjectiveList[distrAdjective(gen)];
     std::uniform_int_distribution<> distrAnimal(0, animalList.size() - 1);
     std::string randomAnimal = animalList[distrAnimal(gen)];
     return randomAdjective + randomAnimal;
 }
References getFileContents(), and getFilePathStart().
Referenced by playGame().
getUserMove()
string GUI::getUserMove (bool canCheck, bool canRaise, bool canFold, bool canCall) static
Prompts the user for their move.
Parameters
canCheck Whether the player can check.
canRaise Whether the player can raise.
canFold Whether the player can fold.
canCall Whether the player can call.
Returns
The move chosen by the user as a string.
Get user move from the terminal
Definition at line 77 of file GUI.cpp.
{
     // Get user move
     // Create message to user based on possible actions
     string message = "";
     if (canFold) {
         message += "fold = f";
     }
     if (canCall) {
         message += ", call = c";
     }
     if (canCheck) {
         message += ", check = a";
     }
     if (canRaise) {
         message += ", raise = r";
     }
     if (message.length() >= 2 && message.substr(0, 2) == ", ") {
         message = message.substr(2);
     }
     message = "Enter your move: (" + message + ") ";
     std::string move;
     std::cout << message; // instead of this we would call display game state which auto adds message
     std::cin >> move;
     while((move == "f" && !canFold) ||
           (move == "a" && !canCheck) ||
           (move == "c" && !canCall) ||
           (move == "r" && !canRaise) ||
           (move != "f" && move != "a" && move != "c" && move != "r")) {
         std::cout << "Invalid move. Please enter a valid move: "; // Chnage message to this
         std::cin >> move;
     }
     return move;
 }
Referenced by HumanPlayer::getMove(), and HumanPlayerTest::SetUp().
optionToViewStats()
void GUI::optionToViewStats (PlayerProfile profile) static
Displays the menu to view player stats.
Definition at line 653 of file GUI.cpp.
{
     // either display stats or return
      std::cout << "Do you want to view your statistics? (y/n): ";
     string decision;
     // Asking the user for y/n
     do {
         std::cin >> decision;
         // Check if the input is valid
         if (decision != "y" && decision != "n") {
             std::cout << "Invalid input. Please enter y or n: ";
         }
     } while (decision != "y" && decision != "n");
     if(decision == "y"){
         displayPlayerStats(player);
     }
     return;
 }
References displayPlayerStats().
Referenced by playGame().
setGame()
void GUI::setGame (Game * game) static
Sets the game object for the GUI.
Parameters
game Pointer to the game object.
Definition at line 33 of file GUI.cpp.
{
     GUI::game = game;
 }
References game.
Referenced by playGame().
signInMenu()
PlayerProfile GUI::signInMenu () static
Prompts the user to sign in.
Returns
The name of the user as a string.
Definition at line 373 of file GUI.cpp.
{
     enum MenuOption { SIGN_IN = 1, CREATE_PROFILE, PLAY_AS_GUEST };
     const std::vector<std::string> acceptedInputs = {"1", "2", "3"};
     std::cout << "Select one of the following options:" << std::endl;
     std::cout << "1. Sign in with a name" << std::endl;
     std::cout << "2. Create profile" << std::endl;
     std::cout << "3. Play as guest" << std::endl;
     std::string input;
     do {
         std::getline(std::cin, input);
         if (std::find(acceptedInputs.begin(), acceptedInputs.end(), input) == acceptedInputs.end()) {
             std::cout << "Invalid input. Please enter a valid option: ";
         }
     } while (std::find(acceptedInputs.begin(), acceptedInputs.end(), input) == acceptedInputs.end());
     MenuOption choice = static_cast<MenuOption>(std::stoi(input));
     switch (choice) {
         case SIGN_IN: {
             std::string name;
             std::cout << "Enter your name: ";
             std::getline(std::cin, name);
             return GUI::getProfile(name);
         }
         case CREATE_PROFILE:
             return GUI::createProfile();
         case PLAY_AS_GUEST: {
             std::string guestName;
             std::cout << "Enter a name for guest play: ";
             std::getline(std::cin, guestName);
             PlayerProfile *temp = new PlayerProfile({guestName});
             temp->isGuest = true;
             return *temp;
         }
         default:
             throw std::runtime_error("Unexpected menu option");
     }
 }
References CREATE_PROFILE, createProfile(), getProfile(), and PlayerProfile::isGuest.
Referenced by getProfile(), and playGame().
Field Documentation
COMMUNITY_CARD_POSITIONS
const Point GUI::COMMUNITY_CARD_POSITIONS = { {84, 23}, {92, 23}, {100, 23}, {108, 23}, {116, 23} } static
Positions for community cards.
Definition at line 55 of file GUI.hpp.
Referenced by displayGameState().
game
Game * GUI::game = nullptr static private
Pointer to the game object used for getting game state information.
Definition at line 37 of file GUI.hpp.
Referenced by displayGameState(), getGame(), and setGame().
PLAYER_BUTTON_POSITIONS
const Point GUI::PLAYER_BUTTON_POSITIONS = { {112, 36}, {68, 36}, {50, 28}, {54, 18}, {94, 15}, {138, 15}, {158, 24}, {152, 32} } static
Positions for player buttons.
Definition at line 58 of file GUI.hpp.
Referenced by displayGameState().
PLAYER_CARD_POSITIONS
const Point GUI::PLAYER_CARD_POSITIONS static
Initial value:
= {
    { {96, 39}, {104, 39} },
    { {30, 37}, {38, 37} },
    { {10, 24}, {18, 24} },
    { {30, 8}, {38, 8} },
    { {97, 2}, {105, 2} },
    { {164, 8}, {172, 8} },
    { {186, 24}, {194, 24} },
    { {164, 37}, {172, 37} },
}
Positions for player cards.
Definition at line 54 of file GUI.hpp.
Referenced by displayGameState().
PLAYER_CURRENT_BETS
const Point GUI::PLAYER_CURRENT_BETS = { {104, 36}, {62, 34}, {50, 26}, {62, 17}, {104, 15}, {146, 17}, {158, 26}, {146, 34} } static
Positions for player current bets.
Definition at line 57 of file GUI.hpp.
Referenced by displayGameState().
PLAYER_EQUITY_POSITION
const Point GUI::PLAYER_EQUITY_POSITION = {{10, 10}, {10, 11}} static
Positions for player equity.
Definition at line 59 of file GUI.hpp.
PLAYER_NAME_POSITIONS
const Point GUI::PLAYER_NAME_POSITIONS = { {104, 46}, {54, 39}, {32, 26}, {54, 10}, {104, 9}, {154, 10}, {175, 26}, {154, 39} } static
Positions for player names.
Definition at line 56 of file GUI.hpp.
Referenced by displayGameState().
The documentation for this class was generated from the following files:
src/GUI.hpp
src/GUI.cpp