Run it Twice: EquityCalculator Class Reference
EquityCalculator Class Reference
Calculates the equity (winning probability) of a poker hand against multiple opponents.
#include <EquityCalculator.hpp>
Public Member Functions
EquityCalculator ()
Constructs an EquityCalculator object.
vector< float > calculateHandEquity (const vector< Card > &hand, const vector< Card > &communityCards, Deck deck, int numPlayers)
Evaluates the equity of a hand against multiple opponents.
vector< float > evaluateHand (const vector< Card > &hand, const vector< Card > &communityCards, Deck deck, int numPlayers)
void buildPreflopEquityCSV ()
Private Attributes
HandEvaluator handEvaluator
Object used for evaluating poker hands.
vector< string > suits = { "Hearts", "Diamonds", "Clubs", "Spades" }
The possible suits in a deck of cards.
vector< string > ranks
The possible ranks in a deck of cards.
int WIN = 1
Constant representing a win.
int DRAW = 0
Constant representing a draw.
int LOSE = -1
Constant representing a loss.
Detailed Description
Calculates the equity (winning probability) of a poker hand against multiple opponents.
Definition at line 21 of file EquityCalculator.hpp.
Constructor & Destructor Documentation
EquityCalculator()
EquityCalculator::EquityCalculator ()
Constructs an EquityCalculator object.
Definition at line 5 of file EquityCalculator.cpp.
{
}
Member Function Documentation
buildPreflopEquityCSV()
void EquityCalculator::buildPreflopEquityCSV ()
Definition at line 149 of file EquityCalculator.cpp.
{
    // Define the suits and ranks
    vector<string> suits = { "Hearts", "Diamonds", "Clubs", "Spades" };
    vector<string> ranks = { "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A" };
    int maxPlayers = 8;
    // Vector to hold all cards
    vector<Card> communityCards;
    EquityCalculator equityCalculator;
    Deck deck;
    int totalHands = 169;
    double currentHand = 0;
    // Open a CSV file for writing
    ofstream outFile(getFileStartPath() + "/preflopEquity.csv");
    if (!outFile) {
        cerr << "Error opening file for writing." << endl;
        return;
    }
    outFile << "FirstCardRank,SecondCardRank,suited,players,winEquity,drawEquity" << endl;
    // calculate pocket pairs
    for (string rank : ranks) {
        vector<Card> hand;
        hand.emplace_back(suits[0], rank);
        hand.emplace_back(suits[1], rank);
        Deck deckCopy(deck);
        deckCopy.remove_card(hand[0]);
        deckCopy.remove_card(hand[1]);
        for (int p = 2; p <= maxPlayers; p++) {
            vector<float> result = equityCalculator.evaluateHand(hand, communityCards, deckCopy, p);
            // Save results to CSV file
            outFile << rank << ","
                << rank << ","
                << "false" << ","
                << p << ","
                << result[0] << ","
                << result[1] << endl;
        }
        currentHand++;
        cout << 100 * currentHand / totalHands << "%" << endl;
    }
    // calculate suited hands
    for (int i = 0; i < ranks.size(); i++) {
        for (int j = i+1; j < ranks.size(); j++) {
            string rank1 = ranks[i];
            string rank2 = ranks[j];
            vector<Card> hand;
            hand.emplace_back(suits[0], rank1);
            hand.emplace_back(suits[0], rank2);
            Deck deckCopy(deck);
            deckCopy.remove_card(hand[0]);
            deckCopy.remove_card(hand[1]);
            for (int p = 2; p <= maxPlayers; p++) {
                vector<float> result = equityCalculator.evaluateHand(hand, communityCards, deckCopy, p);
                // Save results to CSV file
                outFile << rank1 << ","
                    << rank2 << ","
                    << "true" << ","
                    << p << ","
                    << result[0] << ","
                    << result[1] << endl;
                outFile << rank2 << ","
                    << rank1 << ","
                    << "true" << ","
                    << p << ","
                    << result[0] << ","
                    << result[1] << endl;
            }
            currentHand++;
            cout << 100 * currentHand / totalHands << "%" << endl;
        }
    }
    // calculate non-suited hands
    for (int i = 0; i < ranks.size(); i++) {
        for (int j = i + 1; j < ranks.size(); j++) {
            string rank1 = ranks[i];
            string rank2 = ranks[j];
            vector<Card> hand;
            hand.emplace_back(suits[0], rank1);
            hand.emplace_back(suits[1], rank2);
            Deck deckCopy(deck);
            deckCopy.remove_card(hand[0]);
            deckCopy.remove_card(hand[1]);
            for (int p = 2; p <= maxPlayers; p++) {
                vector<float> result = equityCalculator.evaluateHand(hand, communityCards, deckCopy, p);
                // Save results to CSV file
                outFile << rank1 << ","
                    << rank2 << ","
                    << "false" << ","
                    << p << ","
                    << result[0] << ","
                    << result[1] << endl;
                outFile << rank2 << ","
                    << rank1 << ","
                    << "false" << ","
                    << p << ","
                    << result[0] << ","
                    << result[1] << endl;
            }
            currentHand++;
            cout << 100 * currentHand / totalHands << "%" << endl;
        }
    }
}
References evaluateHand(), getFileStartPath(), ranks, Deck::remove_card(), and suits.
Referenced by calculateHandEquity().
calculateHandEquity()
vector< float > EquityCalculator::calculateHandEquity (const vector< Card > & hand, const vector< Card > & communityCards, Deck deck, int numPlayers)
Evaluates the equity of a hand against multiple opponents.
Parameters
hand The player's hand as a vector of Card objects.
communityCards The community cards as a vector of Card objects.
deck The remaining deck of cards after dealing hand and community cards.
numPlayers The number of players in the game.
Returns
A vector of float values representing the equity of the hand.
Definition at line 88 of file EquityCalculator.cpp.
{
    if (communityCards.size() > 0) {
        return evaluateHand(hand, communityCards, deck, numPlayers);
    }
    if (!fileExists(getFileStartPath() + "/preflopEquity.csv")) { buildPreflopEquityCSV(); }
    vector<string> search;
    search.push_back(hand.at(0).rank);
    search.push_back(hand.at(1).rank);
    search.push_back(hand.at(0).suit == hand.at(1).suit ? "true" : "false");
    search.push_back(to_string(numPlayers));
    return findEquity(getFileStartPath() + "/preflopEquity.csv", search);
}
References buildPreflopEquityCSV(), evaluateHand(), fileExists(), findEquity(), and getFileStartPath().
Referenced by Player::get_equity().
evaluateHand()
vector< float > EquityCalculator::evaluateHand (const vector< Card > & hand, const vector< Card > & communityCards, Deck deck, int numPlayers)
Definition at line 104 of file EquityCalculator.cpp.
{
    int iterations = 0;
    double timeToCalculate = 1 * 1000000000; // 1 second in nano seconds
    auto start = std::chrono::high_resolution_clock::now();
    int wins = 0;
    int draws = 0;
    int losses = 0;
    while (true) {
        auto now = std::chrono::high_resolution_clock::now();
        std::chrono::duration<double, std::nano> elapsed = now - start;
        double num = elapsed.count();
        if (elapsed.count() > timeToCalculate) { break; }
        iterations++;
        bool lose = false;
        bool draw = false;
        Deck deckCopy(deck);
        deckCopy.shuffle();
        vector<Card> communityCardsFull(communityCards);
        while (communityCardsFull.size() < 5) {
            communityCardsFull.push_back(deckCopy.deal());
        }
        for (int player = 1; player < numPlayers; player++) {
            if (lose) { continue; }
            // create random hand for opponent
            vector<Card> otherHand;
            for (int i = 0; i < 2; i++) { otherHand.push_back(deckCopy.deal()); }
            // check if we beat opponent's hand
            int outcome = handEvaluator.compareHands(hand, otherHand, communityCardsFull);
            lose = outcome == LOSE;
            if (!draw) {
                draw = outcome == DRAW;
            }
        }
        if (lose) { losses++; continue; }
        if (draw) { draws++; continue; }
        wins++;
    }
    return { 1.0f * wins / iterations, 1.0f * draws / iterations,  1.0f * (iterations - (wins + draws)) / iterations };
}
References HandEvaluator::compareHands(), Deck::deal(), DRAW, handEvaluator, LOSE, and Deck::shuffle().
Referenced by buildPreflopEquityCSV(), and calculateHandEquity().
Field Documentation
DRAW
int EquityCalculator::DRAW = 0 private
Constant representing a draw.
Definition at line 30 of file EquityCalculator.hpp.
Referenced by evaluateHand().
handEvaluator
HandEvaluator EquityCalculator::handEvaluator private
Object used for evaluating poker hands.
Definition at line 23 of file EquityCalculator.hpp.
Referenced by evaluateHand().
LOSE
int EquityCalculator::LOSE = -1 private
Constant representing a loss.
Definition at line 31 of file EquityCalculator.hpp.
Referenced by evaluateHand().
ranks
vector<string> EquityCalculator::ranks private
Initial value:
= { "2", "3", "4", "5", "6", "7", "8", "9", "10",
                      "J", "Q", "K", "A" }
The possible ranks in a deck of cards.
Definition at line 26 of file EquityCalculator.hpp.
                           { "2", "3", "4", "5", "6", "7", "8", "9", "10",
                      "J", "Q", "K", "A" };
Referenced by buildPreflopEquityCSV().
suits
vector<string> EquityCalculator::suits = { "Hearts", "Diamonds", "Clubs", "Spades" } private
The possible suits in a deck of cards.
Definition at line 25 of file EquityCalculator.hpp.
{ "Hearts", "Diamonds", "Clubs", "Spades" };
Referenced by buildPreflopEquityCSV().
WIN
int EquityCalculator::WIN = 1 private
Constant representing a win.
Definition at line 29 of file EquityCalculator.hpp.
The documentation for this class was generated from the following files:
src/EquityCalculator.hpp
src/EquityCalculator.cpp