Run it Twice: Player Class Reference
Player Class Reference abstract
Represents a human player in the poker game.
#include <Player.hpp>
Public Member Functions
Player (const std::string &name, int stack)
Constructs a Player object with a given name and stack.
void bet (int amount)
Places a bet by the player.
int deduct_blind (int amount)
Deducts a blind amount from the player's stack.
void win (int amount)
Adds a winning amount to the player's stack.
int get_stack ()
Gets the current stack of the player.
string get_name ()
Gets the name of the player.
vector< Card > get_hand ()
Gets the player's current hand of cards.
void add_card_to_hand (Card card)
Adds a card to the player's hand.
void clear_hand ()
Clears the player's hand of all cards.
void show_hand ()
Displays the player's current hand.
int get_current_bet ()
Gets the player's current bet in the ongoing hand.
int get_total_bet ()
Gets the total amount the player has bet this hand.
void setTotalBet (int amount)
Sets the total amount the player has bet this hand.
void reset_current_bet ()
Resets the player's current bet to zero.
void reset_total_bet ()
Resets the total amount the player has bet this hand to zero. This is used at the end of a hand to reset the player's total bet.
vector< float > get_equity (vector< Card > communityCards, int numPlayers)
Returns the equity of the players hand for the current stage of the game.
virtual std::string getMove (bool canCheck, bool canRaise, bool canFold, bool canCall, vector< Card > community_cards, int largestBet, int numPlayersInHand, int pot)=0
Gets the player's move during their turn.
virtual int getBetSizing (int minBet, int maxBet)=0
Gets the player's bet sizing during their turn.
virtual int endOfHand ()=0
Handles actions at the end of a hand.
Static Public Member Functions
static bool test_player ()
Tests the Player class functionality.
static string generate_random_name ()
Generates a random name for the player.
Private Attributes
string name
The name of the player.
vector< Card > hand
The player's hand of cards.
int stack
The player's current chip stack.
int current_bet = 0
The player's current bet in the ongoing hand.
int totalBetThisHand = 0
The total amount the player has bet this hand.
Detailed Description
Represents a human player in the poker game.
Represents a player in the poker game.
Definition at line 15 of file Player.hpp.
Constructor & Destructor Documentation
Player()
Player::Player (const std::string & name, int stack)
Constructs a Player object with a given name and stack.
Parameters
name The name of the player.
stack The initial chip stack for the player.
Definition at line 8 of file Player.cpp.
{
    this->name = name;
    this->stack = stack;
}
References name, and stack.
Member Function Documentation
add_card_to_hand()
void Player::add_card_to_hand (Card card)
Adds a card to the player's hand.
Parameters
card The card to be added.
Definition at line 48 of file Player.cpp.
{
    if (this->hand.empty()) {
        // Create a new hand (vector of cards) if the current hand is empty
        this->hand = std::vector<Card>();
    }
    // Add the card to the hand
    this->hand.push_back(card);
}
References hand.
Referenced by TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
bet()
void Player::bet (int amount)
Places a bet by the player.
Parameters
amount The amount to bet.
Definition at line 14 of file Player.cpp.
{
    if(amount > this->stack + this->current_bet) {
        cout << "You don't have enough chips to bet that amount. Betting all in." << endl;
        cout << amount << endl;
        while(true){}
    }
    this->stack -= amount - this->current_bet;
    this->totalBetThisHand += amount - this->current_bet;
    this->current_bet = amount;
}
References current_bet, stack, and totalBetThisHand.
Referenced by BasicPlayer::getBetSizing(), BetterPlayer::getBetSizing(), Game::makeMoveForUser(), TEST_F(), TEST_F(), and TEST_F().
clear_hand()
void Player::clear_hand ()
Clears the player's hand of all cards.
Definition at line 58 of file Player.cpp.
{
    this->hand.clear();
}
References hand.
Referenced by Game::makeMoveForUser(), and TEST_F().
deduct_blind()
int Player::deduct_blind (int amount)
Deducts a blind amount from the player's stack.
Parameters
amount The amount of the blind to deduct.
Returns
The remaining stack after deducting the blind.
Definition at line 25 of file Player.cpp.
{
    this->stack -= amount;
    this->current_bet = amount;
    this->totalBetThisHand += amount;
    return amount;
}
References current_bet, stack, and totalBetThisHand.
Referenced by Game::addBlindsToPot(), and TEST_F().
endOfHand()
virtual int Player::endOfHand () pure virtual
Handles actions at the end of a hand.
Returns
The outcome of the end-of-hand process.
Implemented in BasicPlayer, BetterPlayer, HumanPlayer, HumanPlayer, RandomPlayer, and RandomPlayer.
generate_random_name()
string Player::generate_random_name () static
Generates a random name for the player.
Returns
The randomly generated name.
Definition at line 88 of file Player.cpp.
{
    std::vector<string> animals = {"Dog", "Cat", "Fish", "Bird", "Elephant", "Lion", "Tiger", "Bear", "Penguin", "Panda", "Giraffe", "Horse", "Cow", "Pig", "Sheep", "Goat", "Chicken", "Duck", "Goose", "Turkey", "Ostrich", "Kangaroo", "Koala", "Sloth", "Monkey", "Gorilla", "Chimpanzee", "Orangutan", "Rabbit", "Frog", "Toad", "Turtle", "Snake", "Lizard", "Iguana", "Chameleon", "Alligator", "Crocodile", "Shark", "Whale", "Dolphin", "Octopus", "Squid", "Jellyfish", "Starfish", "Seahorse", "Crab", "Lobster", "Shrimp", "Clam", "Oyster", "Mussel", "Scallop", "Snail", "Slug", "Butterfly", "Moth", "Caterpillar", "Ant", "Bee", "Wasp", "Hornet", "Fly", "Mosquito", "Beetle", "Ladybug", "Grasshopper", "Cricket", "Dragonfly", "Damselfly", "Centipede", "Millipede", "Spider", "Tarantula", "Scorpion", "Tick", "Mite", "Flea", "Bedbug", "Cockroach", "Termite", "Praying Mantis", "Walking Stick", "Earwig", "Silverfish", "Firefly", "Glowworm", "Earthworm", "Leech", "Slug", "Snail", "Clam", "Oyster", "Mussel", "Scallop", "Squid", "Octopus", "Cuttlefish", "Nautilus", "Ammonite", "Trilobite", "Crab", "Lobster", "Shrimp", "Krill", "Barnacle", "Crayfish", "Cockroach", "Termite", "Praying Mantis", "Walking Stick", "Earwig", "Silverfish", "Firefly", "Glowworm", "Earthworm", "Leech", "Slug"};
    std::vector<string> adjectives = {"Happy", "Sad", "Angry", "Excited", "Bored", "Tired", "Energetic", "Lazy", "Calm", "Anxious", "Nervous", "Confident", "Shy", "Brave", "Scared", "Proud", "Embarrassed", "Ashamed", "Guilty", "Jealous", "Envious", "Grateful", "Thankful", "Hopeful", "Hopeless", "Optimistic", "Pessimistic", "Curious", "Inquisitive", "Impatient", "Patient", "Polite", "Rude", "Kind", "Mean", "Generous", "Greedy", "Honest", "Dishonest", "Loyal", "Unfaithful", "Responsible", "Irresponsible", "Reliable", "Unreliable", "Trustworthy", "Untrustworthy", "Fair", "Unfair", "Forgiving", "Unforgiving", "Tolerant", "Intolerant", "Understanding", "Misunderstanding", "Sympathetic", "Unsympathetic", "Empathetic", "Apathetic", "Compassionate", "Heartless", "Caring", "Uncaring", "Affectionate", "Cold", "Warm", "Friendly", "Unfriendly", "Sociable", "Unsociable", "Outgoing", "Shy", "Introverted", "Extroverted", "Optimistic", "Pessimistic", "Cheerful", "Gloomy", "Joyful", "Sorrowful", "Playful", "Serious", "Silly", "Serious", "Clever", "Stupid", "Wise", "Foolish", "Smart", "Dumb", "Intelligent", "Ignorant", "Knowledgeable", "Uninformed", "Educated", "Uneducated", "Informed", "Uninformed", "Experienced", "Inexperienced", "Skilled", "Unskilled", "Talented", "Untalented", "Gifted", "Ungifted", "Creative", "Uncreative", "Imaginative", "Unimaginative", "Innovative", "Uninnovative", "Resourceful", "Unresourceful", "Adventurous" };
    random_device rd;
    mt19937 gen(rd());
    std::uniform_int_distribution<> animalIndex(0, animals.size() - 1);
    std::uniform_int_distribution<> adjectiveIndex(0, adjectives.size() - 1);
    string randomNumber = std::to_string(rand() % 1000 + 1);
    return adjectives[adjectiveIndex(gen)] + " " + animals[animalIndex(gen)] + " " + randomNumber;
}
get_current_bet()
int Player::get_current_bet ()
Gets the player's current bet in the ongoing hand.
Returns
The player's current bet amount.
Definition at line 62 of file Player.cpp.
{
    return this->current_bet;
}
References current_bet.
Referenced by Game::makeMoveForUser(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
get_equity()
vector< float > Player::get_equity (vector< Card > communityCards, int numPlayers)
Returns the equity of the players hand for the current stage of the game.
Parameters
communityCards The community cards to check player cards against.
numPlayers The number of players in the game.
Definition at line 102 of file Player.cpp.
{
    if (this->hand.size() == 0) {
        return { -1, -1 };
    }
    EquityCalculator equityCalculator;
    Deck deck;
    for (Card c : communityCards) { deck.remove_card(c); };
    for (Card c : this->hand) { deck.remove_card(c); };
    return equityCalculator.calculateHandEquity(this->hand, communityCards, deck, numPlayers);
}
References EquityCalculator::calculateHandEquity(), hand, and Deck::remove_card().
Referenced by BasicPlayer::getMove(), BetterPlayer::getMove(), TEST_F(), and TEST_F().
get_hand()
vector< Card > Player::get_hand ()
Gets the player's current hand of cards.
Returns
A vector containing the player's hand of cards.
Definition at line 44 of file Player.cpp.
{
    return this->hand;
}
References hand.
Referenced by GUI::displayPlayerHand(), TEST_F(), TEST_F(), and TEST_F().
get_name()
string Player::get_name ()
Gets the name of the player.
Returns
The player's name.
Definition at line 40 of file Player.cpp.
{
    return this->name;
}
References name.
Referenced by GUI::displayPlayerHand(), GUI::displayPlayerMove(), GUI::displayPlayerStack(), TEST_F(), TEST_F(), and TEST_F().
get_stack()
int Player::get_stack ()
Gets the current stack of the player.
Returns
The player's current chip stack.
Definition at line 36 of file Player.cpp.
                      {
    return this->stack;
}
References stack.
Referenced by GUI::displayPlayerStack(), Game::makeMoveForUser(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
get_total_bet()
int Player::get_total_bet ()
Gets the total amount the player has bet this hand.
Returns
The total amount the player has bet this hand.
Definition at line 66 of file Player.cpp.
{
    return this->totalBetThisHand;
}
References totalBetThisHand.
Referenced by Game::awardPot().
getBetSizing()
virtual int Player::getBetSizing (int minBet, int maxBet) pure virtual
Gets the player's bet sizing during their turn.
Parameters
minBet The minimum bet allowed.
maxBet The maximum bet allowed.
Returns
The player's chosen bet size.
Implemented in HumanPlayer, RandomPlayer, BasicPlayer, BetterPlayer, HumanPlayer, and RandomPlayer.
Referenced by Game::makeMoveForUser().
getMove()
virtual std::string Player::getMove (bool canCheck, bool canRaise, bool canFold, bool canCall, vector< Card > community_cards, int largestBet, int numPlayersInHand, int pot) pure virtual
Gets the player's move during their turn.
Parameters
canCheck Whether the player can check.
canRaise Whether the player can raise.
canFold Whether the player can fold.
canCall Whether the player can call.
Returns
The player's chosen move as a string.
Implemented in BasicPlayer, BetterPlayer, HumanPlayer, and RandomPlayer.
Referenced by Game::bettingRound().
reset_current_bet()
void Player::reset_current_bet ()
Resets the player's current bet to zero.
Definition at line 84 of file Player.cpp.
{
    this->current_bet = 0;
}
References current_bet.
Referenced by Game::makeMoveForUser(), and TEST_F().
reset_total_bet()
void Player::reset_total_bet ()
Resets the total amount the player has bet this hand to zero. This is used at the end of a hand to reset the player's total bet.
Definition at line 76 of file Player.cpp.
{
    this->totalBetThisHand = 0;
}
References totalBetThisHand.
setTotalBet()
void Player::setTotalBet (int amount)
Sets the total amount the player has bet this hand.
Parameters
amount The total amount the player has bet this hand.
Definition at line 80 of file Player.cpp.
{
    this->totalBetThisHand = amount;
}
References totalBetThisHand.
show_hand()
void Player::show_hand ()
Displays the player's current hand.
Definition at line 70 of file Player.cpp.
                       {
    for (Card card : hand) {
        cout << card.get_rank() << " of " << card.get_suit() << endl;
    }
}
References hand.
Referenced by TEST_F().
test_player()
static bool Player::test_player () static
Tests the Player class functionality.
Returns
True if the test passes, otherwise false.
win()
void Player::win (int amount)
Adds a winning amount to the player's stack.
Parameters
amount The amount won.
Definition at line 32 of file Player.cpp.
{
    this->stack += amount;
}
References stack.
Referenced by Game::awardPot(), and TEST_F().
Field Documentation
current_bet
int Player::current_bet = 0 private
The player's current bet in the ongoing hand.
Definition at line 20 of file Player.hpp.
Referenced by bet(), deduct_blind(), get_current_bet(), and reset_current_bet().
hand
vector<Card> Player::hand private
The player's hand of cards.
Definition at line 18 of file Player.hpp.
Referenced by add_card_to_hand(), clear_hand(), get_equity(), get_hand(), and show_hand().
name
string Player::name private
The name of the player.
Definition at line 17 of file Player.hpp.
Referenced by get_name(), and Player().
stack
int Player::stack private
The player's current chip stack.
Definition at line 19 of file Player.hpp.
Referenced by bet(), deduct_blind(), get_stack(), Player(), and win().
totalBetThisHand
int Player::totalBetThisHand = 0 private
The total amount the player has bet this hand.
Definition at line 21 of file Player.hpp.
Referenced by bet(), deduct_blind(), get_total_bet(), reset_total_bet(), and setTotalBet().
The documentation for this class was generated from the following files:
src/Player.hpp
src/Player.cpp