Run it Twice: tests/test_Player.cc File Reference
test_Player.cc File Reference
#include <gtest/gtest.h>
#include <sstream>
#include "../src/Player.hpp"
#include "../src/Card.hpp"
#include "../src/Deck.hpp"
#include "../src/EquityCalculator.hpp"
Data Structures
class PlayerTest
Functions
TEST_F (PlayerTest, Constructor)
TEST_F (PlayerTest, Bet)
TEST_F (PlayerTest, DeductBlind)
TEST_F (PlayerTest, Win)
TEST_F (PlayerTest, GetStack)
TEST_F (PlayerTest, GetName)
TEST_F (PlayerTest, GetHand)
TEST_F (PlayerTest, AddCardToHand)
TEST_F (PlayerTest, ClearHand)
TEST_F (PlayerTest, GetCurrentBet)
TEST_F (PlayerTest, ShowHand)
TEST_F (PlayerTest, ResetCurrentBet)
TEST_F (PlayerTest, GetEquity)
TEST_F (PlayerTest, GetEquityEmptyHand)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 121 of file test_Player.cc.
{
    testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
TEST_F() [1/14]
TEST_F (PlayerTest , AddCardToHand)
Definition at line 74 of file test_Player.cc.
{
    player->add_card_to_hand(Card("Hearts", "A"));
    player->add_card_to_hand(Card("Spades", "K"));
    EXPECT_EQ(player->get_hand().size(), 2);
}
References Player::add_card_to_hand(), and Player::get_hand().
TEST_F() [2/14]
TEST_F (PlayerTest , Bet)
Definition at line 36 of file test_Player.cc.
{
    player->bet(500);
    EXPECT_EQ(player->get_stack(), 500);
    EXPECT_EQ(player->get_current_bet(), 500);
    // Test betting more than available
    std::string output = captureOutput([this]() { player->bet(1000); });
    EXPECT_TRUE(output.find("You don't have enough chips to bet that amount") != std::string::npos);
    EXPECT_EQ(player->get_stack(), 0);
    EXPECT_EQ(player->get_current_bet(), 1000);
}
References Player::bet(), Player::get_current_bet(), and Player::get_stack().
TEST_F() [3/14]
TEST_F (PlayerTest , ClearHand)
Definition at line 80 of file test_Player.cc.
{
    player->add_card_to_hand(Card("Hearts", "A"));
    player->clear_hand();
    EXPECT_TRUE(player->get_hand().empty());
}
References Player::add_card_to_hand(), Player::clear_hand(), and Player::get_hand().
TEST_F() [4/14]
TEST_F (PlayerTest , Constructor)
Definition at line 31 of file test_Player.cc.
{
    EXPECT_EQ(player->get_name(), "TestPlayer");
    EXPECT_EQ(player->get_stack(), 1000);
}
References Player::get_name(), and Player::get_stack().
TEST_F() [5/14]
TEST_F (PlayerTest , DeductBlind)
Definition at line 48 of file test_Player.cc.
{
    int deducted = player->deduct_blind(50);
    EXPECT_EQ(deducted, 50);
    EXPECT_EQ(player->get_stack(), 950);
    EXPECT_EQ(player->get_current_bet(), 50);
}
References Player::deduct_blind(), Player::get_current_bet(), and Player::get_stack().
TEST_F() [6/14]
TEST_F (PlayerTest , GetCurrentBet)
Definition at line 86 of file test_Player.cc.
{
    player->bet(200);
    EXPECT_EQ(player->get_current_bet(), 200);
}
References Player::bet(), and Player::get_current_bet().
TEST_F() [7/14]
TEST_F (PlayerTest , GetEquity)
Definition at line 105 of file test_Player.cc.
{
    player->add_card_to_hand(Card("Hearts", "A"));
    player->add_card_to_hand(Card("Spades", "K"));
    std::vector<Card> communityCards = {Card("Diamonds", "Q"), Card("Clubs", "J"), Card("Hearts", "10")};
    std::vector<float> equity = player->get_equity(communityCards, 2);
    EXPECT_EQ(equity.size(), 2);
    EXPECT_GE(equity[0], 0.0f);
    EXPECT_LE(equity[0], 1.0f);
}
References Player::add_card_to_hand(), and Player::get_equity().
TEST_F() [8/14]
TEST_F (PlayerTest , GetEquityEmptyHand)
Definition at line 115 of file test_Player.cc.
{
    std::vector<Card> communityCards = {Card("Diamonds", "Q"), Card("Clubs", "J"), Card("Hearts", "10")};
    std::vector<float> equity = player->get_equity(communityCards, 2);
    EXPECT_EQ(equity, std::vector<float>{-1, -1});
}
References Player::get_equity().
TEST_F() [9/14]
TEST_F (PlayerTest , GetHand)
Definition at line 68 of file test_Player.cc.
{
    EXPECT_TRUE(player->get_hand().empty());
    player->add_card_to_hand(Card("Hearts", "A"));
    EXPECT_EQ(player->get_hand().size(), 1);
}
References Player::add_card_to_hand(), and Player::get_hand().
TEST_F() [10/14]
TEST_F (PlayerTest , GetName)
Definition at line 64 of file test_Player.cc.
{
    EXPECT_EQ(player->get_name(), "TestPlayer");
}
References Player::get_name().
TEST_F() [11/14]
TEST_F (PlayerTest , GetStack)
Definition at line 60 of file test_Player.cc.
{
    EXPECT_EQ(player->get_stack(), 1000);
}
References Player::get_stack().
TEST_F() [12/14]
TEST_F (PlayerTest , ResetCurrentBet)
Definition at line 99 of file test_Player.cc.
{
    player->bet(200);
    player->reset_current_bet();
    EXPECT_EQ(player->get_current_bet(), 0);
}
References Player::bet(), Player::get_current_bet(), and Player::reset_current_bet().
TEST_F() [13/14]
TEST_F (PlayerTest , ShowHand)
Definition at line 91 of file test_Player.cc.
{
    player->add_card_to_hand(Card("Hearts", "A"));
    player->add_card_to_hand(Card("Spades", "K"));
    std::string output = captureOutput([this]() { player->show_hand(); });
    EXPECT_TRUE(output.find("A of Hearts") != std::string::npos);
    EXPECT_TRUE(output.find("K of Spades") != std::string::npos);
}
References Player::add_card_to_hand(), and Player::show_hand().
TEST_F() [14/14]
TEST_F (PlayerTest , Win)
Definition at line 55 of file test_Player.cc.
{
    player->win(500);
    EXPECT_EQ(player->get_stack(), 1500);
}
References Player::get_stack(), and Player::win().