Run it Twice: tests/test_HumanPlayer.cc File Reference
test_HumanPlayer.cc File Reference
#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include "MockGUI.hpp"
#include "../src/HumanPlayer.hpp"
#include "../src/Player.hpp"
Data Structures
class HumanPlayerTest
Functions
TEST_F (HumanPlayerTest, Constructor)
TEST_F (HumanPlayerTest, GetMove)
TEST_F (HumanPlayerTest, GetBetSizing)
TEST_F (HumanPlayerTest, EndOfHand)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 59 of file test_HumanPlayer.cc.
{
     ::testing::InitGoogleTest(&argc, argv);
     return RUN_ALL_TESTS();
 }
TEST_F() [1/4]
TEST_F (HumanPlayerTest , Constructor)
Definition at line 23 of file test_HumanPlayer.cc.
{
     HumanPlayer player("TestPlayer", 1000);
     EXPECT_EQ(player.get_name(), "TestPlayer");
     EXPECT_EQ(player.get_stack(), 1000);
 }
References Player::get_name(), and Player::get_stack().
TEST_F() [2/4]
TEST_F (HumanPlayerTest , EndOfHand)
Definition at line 49 of file test_HumanPlayer.cc.
{
     HumanPlayer player("TestPlayer", 1000);
     EXPECT_CALL(MockGUI::endOfRoundMenu, ())
         .WillOnce(::testing::Return(1));
     int result = player.endOfHand();
     EXPECT_EQ(result, 1);
 }
References HumanPlayer::endOfHand().
TEST_F() [3/4]
TEST_F (HumanPlayerTest , GetBetSizing)
Definition at line 39 of file test_HumanPlayer.cc.
{
     HumanPlayer player("TestPlayer", 1000);
     EXPECT_CALL(MockGUI::getBetSizing, (50, 200))
         .WillOnce(::testing::Return(100));
     int betSize = player.getBetSizing(50, 200);
     EXPECT_EQ(betSize, 100);
 }
References HumanPlayer::getBetSizing().
TEST_F() [4/4]
TEST_F (HumanPlayerTest , GetMove)
Definition at line 29 of file test_HumanPlayer.cc.
{
     HumanPlayer player("TestPlayer", 1000);
     EXPECT_CALL(MockGUI::getUserMove, (true, true, true, true))
         .WillOnce(::testing::Return("raise"));
     std::string move = player.getMove(true, true, true, true);
     EXPECT_EQ(move, "raise");
 }
References HumanPlayer::getMove().