Run it Twice: tests/test_Card.cc File Reference
test_Card.cc File Reference
#include <gtest/gtest.h>
#include "../src/Card.hpp"
Functions
TEST (TestCard, TestCardConstructor)
TEST (TestCard, TestCardGetSuit)
TEST (TestCard, TestCardGetRank)
TEST (TestCard, TestCardGetCard)
Function Documentation
TEST() [1/4]
TEST (TestCard , TestCardConstructor)
Definition at line 5 of file test_Card.cc.
{
    Card card = Card("Hearts", "Ace");
    ASSERT_EQ(card.get_suit(), "Hearts");
    ASSERT_EQ(card.get_rank(), "Ace");
}
References Card::get_rank(), and Card::get_suit().
TEST() [2/4]
TEST (TestCard , TestCardGetCard)
Definition at line 22 of file test_Card.cc.
{
    Card card = Card("Hearts", "Ace");
    ASSERT_EQ(card.get_card(), "Ace of Hearts");
}
References Card::get_card().
TEST() [3/4]
TEST (TestCard , TestCardGetRank)
Definition at line 17 of file test_Card.cc.
{
    Card card = Card("Hearts", "Ace");
    ASSERT_EQ(card.get_rank(), "Ace");
}
References Card::get_rank().
TEST() [4/4]
TEST (TestCard , TestCardGetSuit)
Definition at line 12 of file test_Card.cc.
{
    Card card = Card("Hearts", "Ace");
    ASSERT_EQ(card.get_suit(), "Hearts");
}
References Card::get_suit().