Run it Twice: tests/test_Game.cc File Reference
test_Game.cc File Reference
#include "gtest/gtest.h"
#include <vector>
#include "../src/Game.hpp"
Data Structures
class GameTest
Functions
TEST_F (GameTest, ConstructorAndGetPlayers)
TEST_F (GameTest, AddPlayer)
TEST_F (GameTest, DealHands)
TEST_F (GameTest, DealFlop)
TEST_F (GameTest, DealTurn)
TEST_F (GameTest, DealRiver)
TEST_F (GameTest, GetPot)
TEST_F (GameTest, GetButton)
TEST_F (GameTest, GetShowdown)
TEST_F (GameTest, Deal)
TEST_F (GameTest, NextStage)
TEST_F (GameTest, GetFinalWinner)
TEST_F (GameTest, GetCurrentMove)
TEST_F (GameTest, ResetPlayerBets)
TEST_F (GameTest, ResetPlayerHands)
TEST_F (GameTest, ResetCommunityCards)
TEST_F (GameTest, AddBlindsToPot)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 220 of file test_Game.cc.
{
     ::testing::InitGoogleTest(&argc, argv);
     return RUN_ALL_TESTS();
 }
TEST_F() [1/17]
TEST_F (GameTest , AddBlindsToPot)
Definition at line 191 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     Player* bigBlind = game.getPlayers()[0];
     Player* smallBlind = game.getPlayers()[1];
     game.addBlindsToPot(bigBlind, smallBlind);
     const int BIG_BLIND = 2;
     const int SMALL_BLIND = 1;
     EXPECT_EQ(game.getPot(), BIG_BLIND + SMALL_BLIND);
 }
References Game::addBlindsToPot(), Game::getPlayers(), and Game::getPot().
TEST_F() [2/17]
TEST_F (GameTest , AddPlayer)
Definition at line 31 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     Player* newPlayer = new HumanPlayer("NewPlayer", 1000);
     game.add_player(newPlayer);
     EXPECT_EQ(game.getPlayers().size(), 3);
 }
References Game::add_player(), and Game::getPlayers().
TEST_F() [3/17]
TEST_F (GameTest , ConstructorAndGetPlayers)
Definition at line 26 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     EXPECT_EQ(game.getPlayers().size(), 2);
 }
References Game::getPlayers().
TEST_F() [4/17]
TEST_F (GameTest , Deal)
Definition at line 114 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     game.deal();
     EXPECT_EQ(game.getPlayers()[0]->get_hand().size(), 2);
     game.currentStage = Stage::FLOP;
     game.deal();
     EXPECT_EQ(game.getCommunityCards().size(), 3);
     game.currentStage = Stage::TURN;
     game.deal();
     EXPECT_EQ(game.getCommunityCards().size(), 4);
     game.currentStage = Stage::RIVER;
     game.deal();
     EXPECT_EQ(game.getCommunityCards().size(), 5);
 }
References Game::currentStage, Game::deal(), FLOP, Game::getCommunityCards(), Game::getPlayers(), RIVER, and TURN.
TEST_F() [5/17]
TEST_F (GameTest , DealFlop)
Definition at line 47 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     game.deal_flop();
     EXPECT_EQ(game.getCommunityCards().size(), 3);
     // Deal three cards and burn one
     EXPECT_EQ(game.deck.get_cards().size(), 48);
 }
References Game::deal_flop(), Game::deck, Deck::get_cards(), and Game::getCommunityCards().
TEST_F() [6/17]
TEST_F (GameTest , DealHands)
Definition at line 38 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     game.deal_hands();
     for (Player* player : game.getPlayers()) {
         EXPECT_EQ(player->get_hand().size(), 2);
     }
     EXPECT_EQ(game.deck.get_cards().size(), 48);
 }
References Game::deal_hands(), Game::deck, Deck::get_cards(), and Game::getPlayers().
TEST_F() [7/17]
TEST_F (GameTest , DealRiver)
Definition at line 63 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     game.deal_river();
     EXPECT_EQ(game.getCommunityCards().size(), 1);
     // Deal one card and burn one
     EXPECT_EQ(game.deck.get_cards().size(), 50);
 }
References Game::deal_river(), Game::deck, Deck::get_cards(), and Game::getCommunityCards().
TEST_F() [8/17]
TEST_F (GameTest , DealTurn)
Definition at line 55 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     game.deal_turn();
     EXPECT_EQ(game.getCommunityCards().size(), 1);
     // Deal one card and burn one
     EXPECT_EQ(game.deck.get_cards().size(), 50);
 }
References Game::deal_turn(), Game::deck, Deck::get_cards(), and Game::getCommunityCards().
TEST_F() [9/17]
TEST_F (GameTest , GetButton)
Definition at line 76 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     EXPECT_EQ(game.getButton(), 0);
 }
References Game::getButton().
TEST_F() [10/17]
TEST_F (GameTest , GetCurrentMove)
Definition at line 161 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     EXPECT_EQ(game.getCurrentMove("a"), Move::CHECK);
     EXPECT_EQ(game.getCurrentMove("c"), Move::CALL);
     EXPECT_EQ(game.getCurrentMove("r"), Move::RAISE);
     EXPECT_EQ(game.getCurrentMove("f"), Move::FOLD);
     EXPECT_EQ(game.getCurrentMove("invalid"), Move::FOLD);
 }
References CALL, CHECK, FOLD, Game::getCurrentMove(), and RAISE.
TEST_F() [11/17]
TEST_F (GameTest , GetFinalWinner)
Definition at line 146 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     std::vector<bool> inGame = {true, false};
     Player* winner = game.get_final_winner(inGame);
     EXPECT_EQ(winner, game.getPlayers()[0]);
 }
References Game::get_final_winner(), and Game::getPlayers().
TEST_F() [12/17]
TEST_F (GameTest , GetPot)
Definition at line 71 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     EXPECT_EQ(game.getPot(), 0);
 }
References Game::getPot().
TEST_F() [13/17]
TEST_F (GameTest , GetShowdown)
Definition at line 81 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     EXPECT_FALSE(game.getShowdown());
 }
References Game::getShowdown().
TEST_F() [14/17]
TEST_F (GameTest , NextStage)
Definition at line 132 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     game.nextStage();
     // Add assertions based on the expected behavior of nextStage()
 }
References Game::nextStage().
TEST_F() [15/17]
TEST_F (GameTest , ResetCommunityCards)
Definition at line 184 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     game.deal_flop();
     game.resetCommunityCards();
     EXPECT_EQ(game.getCommunityCards().size(), 0);
 }
References Game::deal_flop(), Game::getCommunityCards(), and Game::resetCommunityCards().
TEST_F() [16/17]
TEST_F (GameTest , ResetPlayerBets)
Definition at line 170 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     game.getPlayers()[0]->bet(50);
     game.resetPlayerBets();
     EXPECT_EQ(game.getPlayers()[0]->get_current_bet(), 0);
 }
References Game::getPlayers(), and Game::resetPlayerBets().
TEST_F() [17/17]
TEST_F (GameTest , ResetPlayerHands)
Definition at line 177 of file test_Game.cc.
{
     Game game = createGameWithPlayers(2);
     game.deal_hands();
     game.resetPlayerHands();
     EXPECT_EQ(game.getPlayers()[0]->get_hand().size(), 0);
 }
References Game::deal_hands(), Game::getPlayers(), and Game::resetPlayerHands().