Bluron: tests/test_Card.cpp File Reference
test_Card.cpp File Reference
#include "../src/Card.hpp"
#include <cassert>
#include <iostream>
Functions
void test_card ()
int main ()
Function Documentation
main()
int main ()
Definition at line 15 of file test_Card.cpp.
 {
     test_card();
     return 0;
 }
References test_card().
test_card()
void test_card ()
Definition at line 5 of file test_Card.cpp.
 {
     Card card("Hearts", "Ace");
     assert(card.get_suit() == "Hearts" && "Incorrect suit");
     assert(card.get_rank() == "Ace" && "Incorrect rank");
     std::cout << "Card test passed!" << std::endl;
 }
References Card::get_rank(), and Card::get_suit().
Referenced by main().