Run it Twice: tests/test_Deck.cc File Reference
test_Deck.cc File Reference
#include <gtest/gtest.h>
#include "../src/Deck.hpp"
Functions
TEST (TestDeck, TestDeckConstructor)
TEST (TestDeck, TestDeckGetCards)
TEST (TestDeck, TestDeckReset)
TEST (TestDeck, TestDeckShuffle)
TEST (TestDeck, TestDeckDeal)
TEST (TestDeck, TestDeckFindCard)
TEST (TestDeck, TestDeckFindCardNotExist)
TEST (TestDeck, TestDeckRemoveCard)
Function Documentation
TEST() [1/8]
TEST (TestDeck , TestDeckConstructor)
Definition at line 5 of file test_Deck.cc.
{
    Deck deck = Deck();
    vector<Card> cards = deck.get_cards();
    ASSERT_EQ(cards.size(), 52);
    // Check if all the cards are unique
    for (int i = 0; i < cards.size(); i++) {
        for (int j = i + 1; j < cards.size(); j++) {
            const bool checkSuit = cards[i].get_suit() == cards[j].get_suit();
            const bool checkRank = cards[i].get_rank() == cards[j].get_rank();
            ASSERT_FALSE(checkSuit && checkRank);
        }
    }
}
References Deck::get_cards().
TEST() [2/8]
TEST (TestDeck , TestDeckDeal)
Definition at line 62 of file test_Deck.cc.
{
    Deck deck = Deck();
    vector<Card> cards = deck.get_cards();
    Card card = deck.deal();
    vector<Card> newCards = deck.get_cards();
    ASSERT_EQ(cards.size(), 52);
    ASSERT_EQ(newCards.size(), 51);
}
References Deck::deal(), and Deck::get_cards().
TEST() [3/8]
TEST (TestDeck , TestDeckFindCard)
Definition at line 73 of file test_Deck.cc.
{
    Deck deck = Deck();
    Card card = deck.find_card("A", "Hearts");
    ASSERT_EQ(card.get_suit(), "Hearts");
    ASSERT_EQ(card.get_rank(), "A");
}
References Deck::find_card(), Card::get_rank(), and Card::get_suit().
TEST() [4/8]
TEST (TestDeck , TestDeckFindCardNotExist)
Definition at line 81 of file test_Deck.cc.
{
    Deck deck = Deck();
    Card card = deck.find_card("", "");
    ASSERT_EQ(card.get_suit(), "");
    ASSERT_EQ(card.get_rank(), "");
}
References Deck::find_card(), Card::get_rank(), and Card::get_suit().
TEST() [5/8]
TEST (TestDeck , TestDeckGetCards)
Definition at line 23 of file test_Deck.cc.
{
    Deck deck = Deck();
    vector<Card> cards = deck.get_cards();
    ASSERT_EQ(cards.size(), 52);
}
References Deck::get_cards().
TEST() [6/8]
TEST (TestDeck , TestDeckRemoveCard)
Definition at line 89 of file test_Deck.cc.
{
    Deck deck = Deck();
    Card card = deck.find_card("A", "Hearts");
    deck.remove_card(card);
    vector<Card> cards = deck.get_cards();
    bool cardExists = false;
    for (Card c : cards) {
        bool checkSuit = c.get_suit() == card.get_suit();
        bool checkRank = c.get_rank() == card.get_rank();
        if (checkSuit && checkRank) {
            cardExists = true;
            break;
        }
    }
    ASSERT_FALSE(cardExists);
}
References Deck::find_card(), Deck::get_cards(), Card::get_rank(), Card::get_suit(), and Deck::remove_card().
TEST() [7/8]
TEST (TestDeck , TestDeckReset)
Definition at line 30 of file test_Deck.cc.
{
    Deck deck = Deck();
    deck.shuffle();
    deck.reset();
    vector<Card> cards = deck.get_cards();
    ASSERT_EQ(cards.size(), 52);
}
References Deck::get_cards(), Deck::reset(), and Deck::shuffle().
TEST() [8/8]
TEST (TestDeck , TestDeckShuffle)
Definition at line 38 of file test_Deck.cc.
{
    Deck deck = Deck();
    vector<Card> cards = deck.get_cards();
    deck.shuffle();
    vector<Card> shuffledCards = deck.get_cards();
    // Check if the cards are shuffled
    bool isShuffled = false;
    for (int i = 0; i < cards.size(); i++) {
        bool checkSuit = cards[i].get_suit() == shuffledCards[i].get_suit();
        bool checkRank = cards[i].get_rank() == shuffledCards[i].get_rank();
        // If any of the cards are are different, then the deck is shuffled
        if (!checkSuit || !checkRank) {
            isShuffled = true;
            break;
        }
    }
    ASSERT_TRUE(isShuffled);
}
References Deck::get_cards(), and Deck::shuffle().