Run it Twice: tests/test_EquityCalculator.cc File Reference
test_EquityCalculator.cc File Reference
#include <gtest/gtest.h>
#include <fstream>
#include <chrono>
#include <thread>
#include "../src/EquityCalculator.hpp"
Data Structures
class EquityCalculatorTest
Macros
#define MOCK_OS "Unknown"
Functions
std::string getFileStartPath ()
bool fileExists (const std::string &filename)
std::vector< float > findEquity (const std::string &filename, const std::vector< std::string > &searchValues)
TEST_F (EquityCalculatorTest, GetFileStartPath)
TEST_F (EquityCalculatorTest, FileExists)
TEST_F (EquityCalculatorTest, FindEquity)
TEST_F (EquityCalculatorTest, CalculateHandEquity)
TEST_F (EquityCalculatorTest, EvaluateHand)
int main (int argc, char **argv)
Macro Definition Documentation
MOCK_OS
#define MOCK_OS "Unknown"
Definition at line 16 of file test_EquityCalculator.cc.
Function Documentation
fileExists()
bool fileExists (const std::string & filename)
Definition at line 43 of file EquityCalculator.cpp.
{
     struct stat buffer;
     return (stat(filename.c_str(), &buffer) == 0);
 }
Referenced by EquityCalculator::calculateHandEquity(), and TEST_F().
findEquity()
std::vector<float> findEquity (const std::string & filename, const std::vector< std::string > & searchValues)
Definition at line 48 of file EquityCalculator.cpp.
{
     vector<float> equity;
     std::ifstream file(filename);
     if (!file.is_open()) {
         std::cerr << "Error opening file: " << filename << std::endl;
         return equity;
     }
     std::string line;
     while (std::getline(file, line)) {
         std::stringstream ss(line);
         std::string field;
         std::vector<std::string> row;
         while (std::getline(ss, field, ',')) {
             row.push_back(field);
         }
         if (row.size() >= 6) {
             bool match = true;
             for (size_t i = 0; i < 4; ++i) {
                 if (i >= searchValues.size() || row[i] != searchValues[i]) {
                     match = false;
                     break;
                 }
             }
             if (match) {
                 file.close();
                 equity.push_back(stof(row[4]));
                 equity.push_back(stof(row[5]));
                 return equity;
             }
         }
     }
     file.close();
     return equity;
 }
Referenced by EquityCalculator::calculateHandEquity(), and TEST_F().
getFileStartPath()
std::string getFileStartPath ()
Definition at line 9 of file EquityCalculator.cpp.
{
     // Get os type
 #ifdef _WIN32
     std::string os = "Windows";
 #elif __APPLE__
     std::string os = "MacOS";
 #elif __linux__
     std::string os = "Linux";
 #else
     std::string os = "Unknown";
 #endif
     string startPath;
     if (os == "Windows")
     {
         startPath = "../../..";
     }
     else if (os == "MacOS")
     {
         startPath = "..";
     }
     else if (os == "Linux")
     {
         startPath = "..";
     }
     else
     {
         std::cerr << "Unsupported OS" << std::endl;
         return "";
     }
     return startPath;
 }
Referenced by EquityCalculator::buildPreflopEquityCSV(), EquityCalculator::calculateHandEquity(), and TEST_F().
main()
int main (int argc, char ** argv)
Definition at line 143 of file test_EquityCalculator.cc.
{
     testing::InitGoogleTest(&argc, argv);
     return RUN_ALL_TESTS();
 }
TEST_F() [1/5]
TEST_F (EquityCalculatorTest , CalculateHandEquity)
Definition at line 83 of file test_EquityCalculator.cc.
{
     std::vector<Card> hand = {Card("Hearts", "A"), Card("Spades", "K")};
     std::vector<Card> communityCards;
     Deck deck;
     int numPlayers = 2;
     // Test preflop equity calculation
     auto result = calculator.calculateHandEquity(hand, communityCards, deck, numPlayers);
     EXPECT_EQ(result.size(), 2);
     // Test with community cards (postflop)
     communityCards = {Card("Clubs", "7"), Card("Diamonds", "8"), Card("Hearts", "9")};
     result = calculator.calculateHandEquity(hand, communityCards, deck, numPlayers);
     EXPECT_EQ(result.size(), 3);
 }
TEST_F() [2/5]
TEST_F (EquityCalculatorTest , EvaluateHand)
Definition at line 100 of file test_EquityCalculator.cc.
{
     std::vector<Card> hand = {Card("Hearts", "A"), Card("Spades", "K")};
     std::vector<Card> communityCards = {Card("Clubs", "7"), Card("Diamonds", "8"), Card("Hearts", "9")};
     Deck deck;
     int numPlayers = 2;
     auto result = calculator.evaluateHand(hand, communityCards, deck, numPlayers);
     EXPECT_EQ(result.size(), 3);
     EXPECT_GE(result[0], 0.0f);
     EXPECT_LE(result[0], 1.0f);
     EXPECT_GE(result[1], 0.0f);
     EXPECT_LE(result[1], 1.0f);
     EXPECT_GE(result[2], 0.0f);
     EXPECT_LE(result[2], 1.0f);
 }
TEST_F() [3/5]
TEST_F (EquityCalculatorTest , FileExists)
Definition at line 43 of file test_EquityCalculator.cc.
{
     // Create a temporary file
     std::ofstream tempFile("temp.txt");
     tempFile.close();
     EXPECT_TRUE(fileExists("temp.txt"));
     EXPECT_FALSE(fileExists("nonexistent.txt"));
     // Clean up
     std::remove("temp.txt");
 }
References fileExists().
TEST_F() [4/5]
TEST_F (EquityCalculatorTest , FindEquity)
Definition at line 56 of file test_EquityCalculator.cc.
{
     // Create a test CSV file
     std::ofstream testFile("test.csv");
     testFile << "A,K,true,2,0.6,0.1\n";
     testFile << "Q,J,false,3,0.4,0.05\n";
     testFile.close();
     std::vector<std::string> searchValues = {"A", "K", "true", "2"};
     auto result = findEquity("test.csv", searchValues);
     EXPECT_EQ(result.size(), 2);
     EXPECT_FLOAT_EQ(result[0], 0.6f);
     EXPECT_FLOAT_EQ(result[1], 0.1f);
     // Test with non-matching values
     searchValues = {"X", "Y", "false", "4"};
     result = findEquity("test.csv", searchValues);
     EXPECT_TRUE(result.empty());
     // Test with non-existent file
     result = findEquity("nonexistent.csv", searchValues);
     EXPECT_TRUE(result.empty());
     // Clean up
     std::remove("test.csv");
 }
References findEquity().
TEST_F() [5/5]
TEST_F (EquityCalculatorTest , GetFileStartPath)
Definition at line 31 of file test_EquityCalculator.cc.
{
     std::string result = getFileStartPath();
     #ifdef _WIN32
     EXPECT_EQ(result, "../../..");
     #elif __APPLE__ || __linux__
     EXPECT_EQ(result, "..");
     #else
     EXPECT_EQ(result, "");
     #endif
 }
References getFileStartPath().