Bluron: Game Class Reference
Game Class Reference
Manages the state and flow of a poker game.
#include <Game.hpp>
Public Member Functions
Game (vector< Player * > &players)
Constructs a Game object with the given players.
void add_player (Player *player)
Adds a player to the game.
void deal ()
Deals the cards to the players and the community.
void nextStage ()
Advances the game to the next stage.
void deal_hands ()
Deals the hands to the players.
void deal_flop ()
Deals the flop (the first three community cards).
void deal_turn ()
Deals the turn (the fourth community card).
void deal_river ()
Deals the river (the fifth community card).
int getPot ()
Gets the current pot size.
int getButton ()
Gets the current position of the dealer button.
bool getShowdown ()
Checks if the game is at showdown.
void awardPot (vector< Player * > winners)
Awards the pot to the winning players.
vector< Player * > getPlayers ()
Gets the players in the game.
vector< Card > getCommunityCards ()
Gets the community cards on the table.
void resetPlayerBets ()
Resets the current bets of all players.
void resetPlayerHands ()
Resets the hands of all players.
void resetCommunityCards ()
Resets the community cards on the table.
void playHand ()
Plays a single hand of poker.
int makeMoveForUser (const std::string &move, Player *player, int playerIndex, int largestBet)
Processes a move made by the user.
bool bettingRound (vector< bool > &inGame, int largestBet, int numPlayers)
Conducts a betting round.
Player * get_final_winner (vector< bool > &inGame)
Determines the final winner of the game.
vector< Player * > getWinner (vector< Player * > players, const vector< Card > &community_cards, const vector< bool > &inGame)
Determines the winner(s) of the current hand.
Static Public Member Functions
static bool test_game ()
Tests the Game class functionality.
Private Member Functions
Move getCurrentMove (std::string move)
Converts a move string into a Move enum.
void addBlindsToPot (Player *bigBlindPlayer, Player *smallBlindPlayer)
Adds the blinds to the pot from the appropriate players.
Private Attributes
Deck deck
The deck of cards used in the game.
vector< Player * > players
The players participating in the game.
vector< Card > community_cards = {}
The community cards shared among all players.
vector< int > currentBets
The current bets of each player.
const int BIG_BLIND = 2
The value of the big blind.
const int SMALL_BLIND = 1
The value of the small blind.
const int STARTING_STACK = 1000
The initial stack of chips for each player.
int pot = 0
The total amount of chips in the pot.
int button = 0
The position of the dealer button.
int removedPlayerCount = 0
The number of players removed from the game.
bool atShowdown = false
Flag indicating whether the game is at showdown.
Stage currentStage = PREFLOP
The current stage of the hand.
Detailed Description
Manages the state and flow of a poker game.
Definition at line 29 of file Game.hpp.
Constructor & Destructor Documentation
Game()
Game::Game (std::vector< Player * > & players)
Constructs a Game object with the given players.
Parameters
players A vector of pointers to the players in the game.
Constructor for the Game class
Parameters
players vector<Player*>& - A vector of pointers to the players in the game
Definition at line 13 of file Game.cpp.
{
    this->players = players;
    this->deck = Deck();
    this->deck.shuffle();
}
References deck, players, and Deck::shuffle().
Referenced by test_game().
Member Function Documentation
add_player()
void Game::add_player (Player * player)
Adds a player to the game.
Parameters
player Pointer to the player to be added.
Definition at line 19 of file Game.cpp.
{
    players.push_back(player);
}
References players.
Referenced by TestGame::test_add_player(), and test_game().
addBlindsToPot()
void Game::addBlindsToPot (Player * bigBlindPlayer, Player * smallBlindPlayer) private
Adds the blinds to the pot from the appropriate players.
Parameters
bigBlindPlayer Pointer to the player posting the big blind.
smallBlindPlayer Pointer to the player posting the small blind.
Definition at line 522 of file Game.cpp.
{
    this->pot += bigBlindPlayer->deduct_blind(BIG_BLIND);
    this->pot += smallBlindPlayer->deduct_blind(SMALL_BLIND);
}
References BIG_BLIND, Player::deduct_blind(), pot, and SMALL_BLIND.
Referenced by playHand().
awardPot()
void Game::awardPot (vector< Player * > winners)
Awards the pot to the winning players.
Parameters
winners A vector of pointers to the winning players.
Award the pot to the winner of the hand
Parameters
winner Player* - The player object who won the hand
Definition at line 71 of file Game.cpp.
{
    // Loop through the winners and award the pot to each winner
    for (Player* winner : winners) {
        winner->win(pot / winners.size());
    }
    int remainder = pot % winners.size();
    for(int i = 0; i < remainder; i++){
        winners[i]->win(1);
    }
    // Reset the pot
    this->pot = 0;
}
References pot.
Referenced by playHand().
bettingRound()
bool Game::bettingRound (vector< bool > & inGame, int largestBet, int numPlayers)
Conducts a betting round.
Parameters
inGame A vector indicating which players are still in the game.
largestBet The current largest bet on the table.
numPlayers The number of players in the game.
Returns
True if the betting round is successful, otherwise false.
Perform a betting round for the players in the game
Parameters
inGame vector<bool>& - A vector of booleans corresponding to the players in the game
largestBet int - The current largest bet in the game
numPlayers int - The number of players in the game
largestBetPlayer Player* - The player who made the largest bet
preflop bool - Whether the betting round is pre-flop or not
Returns
bool - whether the entire hand should be ended
Definition at line 397 of file Game.cpp.
{
    // TESTING: display game state
    GUI::displayGameState();
    // sleep for 1 second
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    int currentPlayer;
    if(currentStage == Stage::FLOP){   // UTG is first to act if pre-flop
        currentPlayer = button + 3 % numPlayers;
    } else {    // Otherwise, the player to the left of the button is first to act
        currentPlayer = button + 1 % numPlayers;
        while(!inGame[currentPlayer]){
            currentPlayer = (currentPlayer + 1) % numPlayers;
        }
    }
    Player* largestBetPlayer = this->getPlayers()[currentPlayer];
    // Loop for the betting round
    while(true) {
        GUI::displayGameState();
        // End the betting round if there is only one player left in the game
        if (count(inGame.begin(), inGame.end(), true) == 1) {
            return true;
        }
        // If the player is still in the game
        if (inGame[currentPlayer]) {
            Player* player = this->getPlayers()[currentPlayer];
            // TODO: make vars for stack size, current bet etc
            bool canCheck = (largestBet == this->getPlayers()[currentPlayer]->get_current_bet()) || (this->getPlayers()[currentPlayer]->get_stack() == 0);
            bool canRaise = this->getPlayers()[currentPlayer]->get_stack() + this->getPlayers()[currentPlayer]->get_current_bet() > largestBet;
            // A player can only fold or call if they are not the largest better
            bool canFold = this->getPlayers()[currentPlayer]->get_current_bet() != largestBet && this->getPlayers()[currentPlayer]->get_stack() > 0;
            bool canCall = canFold;
            // Get the player's move
            string move = player->getMove(canCheck, canRaise, canFold, canCall);
            // Perform the move for the player
            int betSize = makeMoveForUser(move, this->getPlayers()[currentPlayer], currentPlayer, largestBet);
            std::this_thread::sleep_for(std::chrono::milliseconds(2000));
            // If the player has folded, update the inGame vector
            if (betSize == -1) {
                inGame[currentPlayer] = false;
                continue;
            }
            // Update the largest bet if the player has bet more than the current largest bet
            if (betSize > largestBet) {
                largestBet = betSize;
                largestBetPlayer = this->getPlayers()[currentPlayer];
            }
             GUI::displayGameState();
             std::this_thread::sleep_for(std::chrono::milliseconds(2000));
        }
        // Move to the next player
        currentPlayer = (currentPlayer + 1) % numPlayers;
        // If we have looped back to the player who made the largest bet, break
        if (this->getPlayers()[currentPlayer] == largestBetPlayer) {
            return false;
        }
        // Check if the stack size of all players in the game is 0
        bool allPlayersStacksZero = true;
        for(int i = 0; i < numPlayers; i++){
            if(inGame[i] && this->getPlayers()[i]->get_stack() > 0){
                allPlayersStacksZero = false;
                break;
            }
        }
        if(allPlayersStacksZero){
            return true;
        }
    }
}
References button, currentStage, GUI::displayGameState(), FLOP, Player::getMove(), getPlayers(), and makeMoveForUser().
Referenced by playHand().
deal()
void Game::deal ()
Deals the cards to the players and the community.
Deal cards to the table based on the current stage of the game
Definition at line 234 of file Game.cpp.
               {
    // Check the game stage and deal the appropriate cards
    switch (currentStage) {
        case PREFLOP:
            this->deal_hands();
            break;
        case FLOP:
            this->deal_flop();
            break;
        case TURN:
            this->deal_turn();
            break;
        case RIVER:
            this->deal_river();
            break;
    }
    // Move to the next stage
    this->nextStage();
}
References currentStage, deal_flop(), deal_hands(), deal_river(), deal_turn(), FLOP, nextStage(), PREFLOP, RIVER, and TURN.
Referenced by playHand().
deal_flop()
void Game::deal_flop ()
Deals the flop (the first three community cards).
Definition at line 30 of file Game.cpp.
                     {
    deck.deal();    // Burn card
    for (int i = 0; i < 3; i++) {
        community_cards.push_back(deck.deal()); // Deal 3 cards for the flop
    }
}
References community_cards, Deck::deal(), and deck.
Referenced by deal(), and test_game().
deal_hands()
void Game::deal_hands ()
Deals the hands to the players.
Definition at line 23 of file Game.cpp.
                      {
    for (Player* player : players) {
        player->add_card_to_hand(deck.deal()); // Deal the first card to the player
        player->add_card_to_hand(deck.deal()); // Deal the second card to the player
    }
}
References Deck::deal(), deck, and players.
Referenced by deal(), TestGame::test_deal_hands(), and test_game().
deal_river()
void Game::deal_river ()
Deals the river (the fifth community card).
Definition at line 42 of file Game.cpp.
                      {
    deck.deal();    // Burn card
    community_cards.push_back(deck.deal()); // Deal 1 card for the river
}
References community_cards, Deck::deal(), and deck.
Referenced by deal(), and test_game().
deal_turn()
void Game::deal_turn ()
Deals the turn (the fourth community card).
Definition at line 37 of file Game.cpp.
                     {
    deck.deal();    // Burn card
    community_cards.push_back(deck.deal()); // Deal 1 card for the turn
}
References community_cards, Deck::deal(), and deck.
Referenced by deal(), and test_game().
get_final_winner()
Player * Game::get_final_winner (vector< bool > & inGame)
Determines the final winner of the game.
Parameters
inGame A vector indicating which players are still in the game.
Returns
Pointer to the final winning player.
Get the final winner of the hand- given that there is only one player left
Parameters
inGame vector<bool>& - A vector of booleans corresponding to the players in the game
Returns
Player* - The final winner of the hand
Definition at line 383 of file Game.cpp.
{
    Player *winner = this->getPlayers()[find(inGame.begin(), inGame.end(), true) - inGame.begin()];
    return winner;
}
References getPlayers().
getButton()
int Game::getButton ()
Gets the current position of the dealer button.
Returns
The index of the dealer button.
Definition at line 59 of file Game.cpp.
                    {
    return button;
}
References button.
Referenced by GUI::displayGameState().
getCommunityCards()
std::vector< Card > Game::getCommunityCards ()
Gets the community cards on the table.
Returns
A vector of the community cards.
Definition at line 51 of file Game.cpp.
{
    return community_cards;
}
References community_cards.
Referenced by GUI::displayGameState().
getCurrentMove()
Move Game::getCurrentMove (std::string move) private
Converts a move string into a Move enum.
Parameters
move The move as a string.
Returns
The corresponding Move enum value.
Private method used for converting a string move to a Move enum
Parameters
move string - The move to convert
Returns
Move - The converted move
Definition at line 486 of file Game.cpp.
{
    // Strip the move of any whitespace
    move.erase(remove_if(move.begin(), move.end(), ::isspace), move.end());
    switch (move[0]) {
        case 'a':
            return Move::CHECK;
        case 'c':
            return Move::CALL;
        case 'r':
            return Move::RAISE;
        case 'f':
            return Move::FOLD;
        default:
            return Move::FOLD;
    }
}
References CALL, CHECK, FOLD, and RAISE.
Referenced by makeMoveForUser().
getPlayers()
std::vector< Player * > Game::getPlayers ()
Gets the players in the game.
Returns
A vector of pointers to the players.
Definition at line 47 of file Game.cpp.
{
    return players;
}
References players.
Referenced by bettingRound(), GUI::displayGameState(), get_final_winner(), playHand(), resetPlayerBets(), resetPlayerHands(), TestGame::test_add_player(), TestGame::test_deal_hands(), and test_game().
getPot()
int Game::getPot ()
Gets the current pot size.
Returns
The total amount of chips in the pot.
Definition at line 55 of file Game.cpp.
                 {
    return pot;
}
References pot.
Referenced by GUI::displayGameState().
getShowdown()
bool Game::getShowdown ()
Checks if the game is at showdown.
Returns
True if the game is at showdown, otherwise false.
Definition at line 63 of file Game.cpp.
                       {
    return atShowdown;
}
References atShowdown.
Referenced by GUI::displayGameState().
getWinner()
vector< Player * > Game::getWinner (vector< Player * > players, const vector< Card > & community_cards, const vector< bool > & inGame)
Determines the winner(s) of the current hand.
Parameters
players A vector of pointers to the players in the game.
community_cards A vector of community cards.
inGame A vector indicating which players are still in the game.
Returns
A vector of pointers to the winning players.
Definition at line 527 of file Game.cpp.
{
    vector<Player*> winners;
    vector<vector<Card>> playerHands;
    vector<Player*> playersInGame;
    HandEvaluator handEvaluator = HandEvaluator();
    for(int i = 0; i < players.size(); i++){
        if(inGame[i]){
            vector<Card> playerHand = players[i]->get_hand();
            playerHands.push_back(playerHand);
            playersInGame.push_back(players[i]);
        }
    }
    vector<bool> winningIndex = handEvaluator.evaluateTable(playerHands, community_cards);
    for(int i = 0; i < winningIndex.size(); i++){
        if(winningIndex[i]){
            winners.push_back(playersInGame[i]);
            // print the name of the winner
            // cout << playersInGame[i]->get_name() << endl;
        }
    }
    return winners;
}
References community_cards, HandEvaluator::evaluateTable(), and players.
Referenced by playHand().
makeMoveForUser()
int Game::makeMoveForUser (const std::string & move, Player * player, int playerIndex, int largestBet)
Processes a move made by the user.
Parameters
move The move as a string.
player Pointer to the player making the move.
playerIndex The index of the player.
largestBet The current largest bet on the table.
Returns
The result of the move as an integer.
Perform a move for a user based on the provided move string
Parameters
move string - The move to perform received from the user input
player Player* - The player object to perform the move for
pot int - The current pot size
Definition at line 90 of file Game.cpp.
{
    Move currentMove = getCurrentMove(move);
    // Perform correct move on the player's object
    switch (currentMove) {
        case Move::CALL: {
            int callAmount = largestBet;
            // Check the call amount is less than the player's stack
            if (callAmount > player->get_stack() + player->get_current_bet()) {
                callAmount = player->get_stack() + player->get_current_bet();
            }
            this->pot += callAmount - player->get_current_bet();
            player->bet(callAmount);
            GUI::displayPlayerMove(player, "Call", -1);
            return largestBet;
        }
        case Move::RAISE: {
            int raiseAmount = player->getBetSizing(largestBet+BIG_BLIND, player->get_stack() + player->get_current_bet());
            this->pot += raiseAmount - player->get_current_bet();
            player->bet(raiseAmount);
            GUI::displayPlayerMove(player, "Raise", raiseAmount);
            return raiseAmount;
        }
        case Move::CHECK: {
            GUI::displayPlayerMove(player, "Check", -1);
            return player->get_current_bet();
        }
        case Move::FOLD: {
            player->clear_hand();
            player->reset_current_bet();
            GUI::displayPlayerMove(player, "Fold", -1);
            return -1;  // Used to remove the player from the hand
        }
    }
}
References Player::bet(), BIG_BLIND, CALL, CHECK, Player::clear_hand(), GUI::displayPlayerMove(), FOLD, Player::get_current_bet(), Player::get_stack(), Player::getBetSizing(), getCurrentMove(), pot, RAISE, and Player::reset_current_bet().
Referenced by bettingRound().
nextStage()
void Game::nextStage ()
Advances the game to the next stage.
Move to the next stage of the game
Definition at line 258 of file Game.cpp.
                    {
    // Check the game stage and move to the next stage
    switch (currentStage) {
        case Stage::PREFLOP:
            currentStage = Stage::FLOP;
            break;
        case Stage::FLOP:
            currentStage = Stage::TURN;
            break;
        case Stage::TURN:
            currentStage = Stage::RIVER;
            break;
        case Stage::RIVER:
            currentStage = Stage::PREFLOP;
            break;
    }
}
References currentStage, FLOP, PREFLOP, RIVER, and TURN.
Referenced by deal().
playHand()
void Game::playHand ()
Plays a single hand of poker.
Play a hand of poker
Called in main.cpp to play a hand of poker
Definition at line 281 of file Game.cpp.
                    {
    // Deal cards out to the table
    this->deal();
    // Store the number of players in the hand
    int numPlayers = this->getPlayers().size();
    // A vector of booleans corresponding to the players in the game - keep track of who is still in the hand
    vector<bool> inGame = vector<bool>(numPlayers, true);
    // Get the small blind and big blind players
    Player* smallBlindPlayer = this->getPlayers()[(button + 1) % numPlayers];
    Player* bigBlindPlayer = this->getPlayers()[(button + 2) % numPlayers];
    // Extract blinds from the players and add them to the pot
    this->addBlindsToPot(bigBlindPlayer, smallBlindPlayer);
    int largestBet = BIG_BLIND;
    Player* winner = nullptr;
    // A loop for the 4 possible betting rounds
    for(int i = 0; i < 4; i ++){
        if(this->bettingRound(inGame, largestBet, numPlayers)){
            resetPlayerBets();
            break;
        }
        if(i != 3){
            this->deal();
        }
        largestBet = 0;
        resetPlayerBets();
    }
    vector<Player*> winners = this->getWinner(this->getPlayers(), this->community_cards, inGame);
    //GUI::displayCommunityCards(community_cards);
    atShowdown = count(inGame.begin(), inGame.end(), true) > 1;
    GUI::displayGameState();
    // sleep for 1 second
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    // Award the pot to the winner/s
    this->awardPot(winners);
    GUI::displayGameState();
    // sleep for 1 second
    std::this_thread::sleep_for(std::chrono::milliseconds(2000));
    atShowdown = false;
    // Move the button
    this->button = (this->button + 1) % numPlayers;
    // Reset all hands
    this->resetPlayerHands();
    // Reset the community cards
    this->resetCommunityCards();
    // Reset the deck
    this->deck.reset();
    // Reset the game stage
    this->currentStage = PREFLOP;
    // TESTING: check that the sum of all player stacks is the same as the starting stack
    int totalStack = 0;
    for (Player* player : this->getPlayers()) {
        totalStack += player->get_stack();
        if(player->get_stack() <= 0){
            cout << player->get_name() << "'s stack: " << player->get_stack() << endl;
            cout << "Player stack too small, removing from game" << endl;
            // Remove the player from the players vector
            this->players.erase(remove(players.begin(), players.end(), player), players.end());
            this->removedPlayerCount++;
            // Print all the names of the players in the game
            for (Player* player : this->getPlayers()) {
                cout << player->get_name() << endl;
            }
            // print the length of the players vector
            cout << "Length of players vector: " << this->getPlayers().size() << endl;
            // while(true){}
        }
    }
    int totalChipsInGame = STARTING_STACK*(this->removedPlayerCount + this->players.size());
    if (totalStack != totalChipsInGame) {
        cout << "Total stack is not " << totalChipsInGame << endl;
        cout << "Total stack is " << totalStack << endl;
        // print the stacks of all players
        for (Player* player : this->getPlayers()) {
            cout << player->get_name() << "'s stack: " << player->get_stack() << endl;
        }
        while(true){}
    }
}
References addBlindsToPot(), atShowdown, awardPot(), bettingRound(), BIG_BLIND, button, community_cards, currentStage, deal(), deck, GUI::displayGameState(), getPlayers(), getWinner(), players, PREFLOP, removedPlayerCount, Deck::reset(), resetCommunityCards(), resetPlayerBets(), resetPlayerHands(), and STARTING_STACK.
Referenced by main().
resetCommunityCards()
void Game::resetCommunityCards ()
Resets the community cards on the table.
Definition at line 518 of file Game.cpp.
{
    this->community_cards.clear();
}
References community_cards.
Referenced by playHand().
resetPlayerBets()
void Game::resetPlayerBets ()
Resets the current bets of all players.
Definition at line 505 of file Game.cpp.
{
    for (Player* player : this->getPlayers()) {
        player->reset_current_bet();
    }
}
References getPlayers().
Referenced by playHand().
resetPlayerHands()
void Game::resetPlayerHands ()
Resets the hands of all players.
Definition at line 512 of file Game.cpp.
{
    for (Player* player : this->getPlayers()) {
        player->clear_hand();
    }
}
References getPlayers().
Referenced by playHand().
test_game()
bool Game::test_game () static
Tests the Game class functionality.
Returns
True if the test passes, otherwise false.
Static method to test the Game class
Returns
bool - Whether the tests passed
Definition at line 138 of file Game.cpp.
                     {
    vector<Player*> players;
    HumanPlayer player1 = HumanPlayer("Jess", 1000);
    RandomPlayer player2 = RandomPlayer("James", 1000);
    players.push_back(&player1);
    players.push_back(&player2);
    Game game = Game(players);
    // Game should start with 52 cards
    if (game.deck.get_cards().size() != 52) {
        std::cout << "Deck does not have 52 cards" << std::endl;
        return false;
    }
    // Checking deal_hand
    game.deal_hands();
    for (Player* player : game.getPlayers()) {
        if (player->get_hand().size() != 2) {
            std::cout << "Player does not have 2 cards in hand" << std::endl;
            return false;
        }
    }
    if (game.deck.get_cards().size() != 48) {
        std::cout << "Deck does not have 48 cards" << std::endl;
        return false;
    }
    // Checking deal_flop
    game.deal_flop();
    if (game.community_cards.size() != 3) {
        std::cout << "Flop does not have 3 cards" << std::endl;
        return false;
    }
    if (game.deck.get_cards().size() != 44) {
        std::cout << "Deck does not have 45 cards" << std::endl;
        return false;
    }
    // Checking deal_turn
    game.deal_turn();
    if (game.community_cards.size() != 4) {
        std::cout << "Turn does not have 4 cards" << std::endl;
        return false;
    }
    if (game.deck.get_cards().size() != 42) {
        std::cout << "Deck does not have 44 cards" << std::endl;
        return false;
    }
    // Checking deal_river
    game.deal_river();
    if (game.community_cards.size() != 5) {
        std::cout << "River does not have 5 cards" << std::endl;
        return false;
    }
    if (game.deck.get_cards().size() != 40) {
        std::cout << "Deck does not have 42 cards" << std::endl;
        return false;
    }
    // Checking getPlayers
    if (game.getPlayers().size() != 2) {
        std::cout << "Game does not have 3 players" << std::endl;
        return false;
    }
    if (game.getPlayers()[0]->get_name() != "Jess") {
        std::cout << "Player 1 is not Jess" << std::endl;
        return false;
    }
    if (game.getPlayers()[1]->get_name() != "James") {
        std::cout << "Player 2 is not James" << std::endl;
        return false;
    }
    // Checking add_player
    HumanPlayer player3 = HumanPlayer("Corban", 1000);
    game.add_player(&player3);
    if (game.getPlayers().size() != 3) {
        std::cout << "Game does not have 3 players" << std::endl;
        return false;
    }
    // Free memory
    // for (Player* player : game.getPlayers()) {
    //     delete player;
    // }
    return true;
}
References add_player(), community_cards, deal_flop(), deal_hands(), deal_river(), deal_turn(), deck, Game(), Deck::get_cards(), getPlayers(), and players.
Referenced by uniTest().
Field Documentation
atShowdown
bool Game::atShowdown = false private
Flag indicating whether the game is at showdown.
Definition at line 42 of file Game.hpp.
Referenced by getShowdown(), and playHand().
BIG_BLIND
const int Game::BIG_BLIND = 2 private
The value of the big blind.
Definition at line 36 of file Game.hpp.
Referenced by addBlindsToPot(), makeMoveForUser(), and playHand().
button
int Game::button = 0 private
The position of the dealer button.
Definition at line 40 of file Game.hpp.
Referenced by bettingRound(), getButton(), and playHand().
community_cards
vector<Card> Game::community_cards = {} private
The community cards shared among all players.
Definition at line 33 of file Game.hpp.
{};
Referenced by deal_flop(), deal_river(), deal_turn(), getCommunityCards(), getWinner(), playHand(), resetCommunityCards(), and test_game().
currentBets
vector<int> Game::currentBets private
The current bets of each player.
Definition at line 34 of file Game.hpp.
currentStage
Stage Game::currentStage = PREFLOP private
The current stage of the hand.
Definition at line 44 of file Game.hpp.
Referenced by bettingRound(), deal(), nextStage(), and playHand().
deck
Deck Game::deck private
The deck of cards used in the game.
Definition at line 31 of file Game.hpp.
Referenced by deal_flop(), deal_hands(), deal_river(), deal_turn(), Game(), playHand(), and test_game().
players
vector<Player*> Game::players private
The players participating in the game.
Definition at line 32 of file Game.hpp.
Referenced by add_player(), deal_hands(), Game(), getPlayers(), getWinner(), playHand(), and test_game().
pot
int Game::pot = 0 private
The total amount of chips in the pot.
Definition at line 39 of file Game.hpp.
Referenced by addBlindsToPot(), awardPot(), getPot(), and makeMoveForUser().
removedPlayerCount
int Game::removedPlayerCount = 0 private
The number of players removed from the game.
Definition at line 41 of file Game.hpp.
Referenced by playHand().
SMALL_BLIND
const int Game::SMALL_BLIND = 1 private
The value of the small blind.
Definition at line 37 of file Game.hpp.
Referenced by addBlindsToPot().
STARTING_STACK
const int Game::STARTING_STACK = 1000 private
The initial stack of chips for each player.
Definition at line 38 of file Game.hpp.
Referenced by playHand().
The documentation for this class was generated from the following files:
src/Game.hpp
src/Game.cpp