Bluron: Deck Class Reference
Deck Class Reference
Represents a deck of playing cards, providing functionality to shuffle, deal, and manage the deck.
#include <Deck.hpp>
Public Member Functions
Deck ()
Constructs a Deck object and initializes the deck with all 52 cards.
void shuffle ()
Shuffles the deck of cards.
Card deal ()
Deals a card from the top of the deck.
vector< Card > get_cards ()
Retrieves the current set of cards in the deck.
Card find_card (const string &rank, const string &suit)
Finds a specific card in the deck based on rank and suit.
void remove_card (Card card)
Removes a specified card from the deck.
void reset ()
Resets the deck to its initial state with all 52 cards.
Static Public Member Functions
static bool test_deck ()
Tests the Deck class functionality.
Private Attributes
vector< Card > cards
The collection of cards in the deck.
Detailed Description
Represents a deck of playing cards, providing functionality to shuffle, deal, and manage the deck.
Definition at line 13 of file Deck.hpp.
Constructor & Destructor Documentation
Deck()
Deck::Deck ()
Constructs a Deck object and initializes the deck with all 52 cards.
Definition at line 10 of file Deck.cpp.
           {
    string suits[] = {"Hearts", "Diamonds", "Clubs", "Spades"};
    string ranks[] = {"2", "3", "4", "5", "6", "7", "8", "9", "10",
                      "J", "Q", "K", "A"};
    for (const string& suit : suits) {
        for (const string& rank : ranks) {
            cards.push_back(Card(suit, rank));
        }
    }
}
References cards.
Referenced by test_deck().
Member Function Documentation
deal()
Card Deck::deal ()
Deals a card from the top of the deck.
Returns
The top card from the deck.
Definition at line 50 of file Deck.cpp.
                {
    Card card = cards.back();
    cards.pop_back();
    return card;
}
References cards.
Referenced by Game::deal_flop(), Game::deal_hands(), Game::deal_river(), Game::deal_turn(), and EquityCalculator::evaluateHand().
find_card()
Card Deck::find_card (const string & rank, const string & suit)
Finds a specific card in the deck based on rank and suit.
Parameters
rank The rank of the card to find.
suit The suit of the card to find.
Returns
The Card object matching the specified rank and suit.
Find a specific card in the deck
Parameters
rank string - Rank of the card
suit string - Suit of the card
Definition at line 63 of file Deck.cpp.
{
    for (Card card : cards) {
        if (card.get_suit() == suit && card.get_rank() == rank) {
            return card;
        }
    }
    return Card("", "");
}
References cards.
get_cards()
vector< Card > Deck::get_cards ()
Retrieves the current set of cards in the deck.
Returns
A vector of Card objects representing the current deck.
Definition at line 37 of file Deck.cpp.
{
    return cards;
}
References cards.
Referenced by TestGame::test_deal_hands(), test_deck(), test_deck(), and Game::test_game().
remove_card()
void Deck::remove_card (Card card)
Removes a specified card from the deck.
Parameters
card The Card object to be removed.
Remove a specific card from the deck
Parameters
card Card - Card to remove
Definition at line 77 of file Deck.cpp.
{
    for (int i = 0; i < cards.size(); i++) {
        if (cards[i].get_suit() == card.get_suit() && cards[i].get_rank() == card.get_rank()) {
            cards.erase(cards.begin() + i);
            break;
        }
    }
}
References cards, Card::get_rank(), and Card::get_suit().
reset()
void Deck::reset ()
Resets the deck to its initial state with all 52 cards.
Definition at line 23 of file Deck.cpp.
                 {
    this->cards.clear();
    string suits[] = {"Hearts", "Diamonds", "Clubs", "Spades"};
    string ranks[] = {"2", "3", "4", "5", "6", "7", "8", "9", "10",
                      "J", "Q", "K", "A"};
    cards.clear();
    for (const string& suit : suits) {
        for (const string& rank : ranks) {
            cards.push_back(Card(suit, rank));
        }
    }
    shuffle();
}
References cards, and shuffle().
Referenced by Game::playHand().
shuffle()
void Deck::shuffle ()
Shuffles the deck of cards.
Definition at line 41 of file Deck.cpp.
                   {
    // Create a random device and use it to seed the Mersenne Twister engine
    random_device rd;
    mt19937 g(rd());
    // Shuffle the deck
    std::shuffle(cards.begin(), cards.end(), g);
    }
References cards.
Referenced by EquityCalculator::evaluateHand(), Game::Game(), reset(), test_deck(), and test_deck().
test_deck()
bool Deck::test_deck () static
Tests the Deck class functionality.
Returns
True if the test passes, otherwise false.
Definition at line 87 of file Deck.cpp.
                     {
    vector<Card> allCardsInDeck;
    Deck deck = Deck();
    deck.shuffle();
    // Check that all the cards in the deck are unique and not empty
    for (Card card : deck.get_cards()) {
        // Check if the cards are empty
        if (card.get_suit() == "" || card.get_rank() == "") {
            std::cout << "Card is empty" << std::endl;
            return false;
        }
        // Check if current card is in the vector of all cards
        for (Card c : allCardsInDeck) {
            if (c.get_suit() == card.get_suit() && c.get_rank() == card.get_rank()) {
                std::cout << "Card is not unique" << std::endl;
                return false;
            }
        }
        // Add the card to the vector of all cards
        allCardsInDeck.push_back(card);
    }
    // Free memory
    allCardsInDeck.clear();
    return true;
}
References Deck(), get_cards(), and shuffle().
Referenced by uniTest().
Field Documentation
cards
vector<Card> Deck::cards private
The collection of cards in the deck.
Definition at line 15 of file Deck.hpp.
Referenced by deal(), Deck(), find_card(), get_cards(), remove_card(), reset(), and shuffle().
The documentation for this class was generated from the following files:
src/Deck.hpp
src/Deck.cpp